### ISSUE TITLE
Mensagens duplicadas no fórum

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#1]
As mensagens do fórum ficam duplicadas a cada edição. O correto é deixar apenas uma (pode ser a original pois não rola a mais recente, acho).

**Comment by gusfune** [comment]
Consegue me linkar um exemplo @gustavogitti? Ajudaria pra tentar resolver. Dai preciso pensar em uma solução pois cada update o Wordpress conta como um "notification_post" separado e por isso entram duplicados, pois entende que são coisas distintas, e não deveria ser. Pode estar ligado ao S2Member, mas preciso testar tendo mais informações.

**Comment by gustavogitti** [comment]
Gus, eu apago todas. Mas aqui tem um exemplo:

https://olugar.org/atividade/?acpage=4

![screen shot 2016-08-31 at 10 05 09 am](https://cloud.githubusercontent.com/assets/21227612/18129735/74aa78d6-6f62-11e6-836a-33d2fa772fec.png)

**Comment by gustavogitti** [comment]
Parece que isso acontece dentro de algum período de edição (tipo os 30 min que a gente deixa). Pois agora editei depois (coisa que só admin faz) e não duplicou... Mas antes isso não rolava. E teve uma vez que você corrigiu quando apontei esse problema.

**Comment by gusfune** [comment]
Achei o problema, é um bug do BBPress que não foi corrigido, mas reportado tem meses.
Ajustei direto o arquivo que tava causando isso, testei, não deve voltar. Ta direto em produção pois no Beta tão tava replicando.
Também fiz uma nota na documentação do GitHub pra caso atualizemos o BBPress isso se perca.
