### ISSUE TITLE
Melhoria no fluxo de renovação

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#101]
Gus,

Se o usuário já possuir uma subscription ativa, com um membership plan válido, não pode deixar ele pagar de novo. Nesse caso, precisamos mostrar uma mensagem do tipo: "Você já possui uma assinatura ativa, Clique aqui para entrar no lugar"

**Comment by gusfune** [comment]
@eduardoamuri, subi um ajuste que verificar se o usuário ta no checkout ou voltar e redireciona pra home logada, assim evitamos uma página intermediária. Ok? Pode avaliar se gosta ou se prefere fazer de outra forma?

**Comment by eduardoamuri** [comment]
Gus,

Pensamos melhor aqui e meu pedido foi uma cagada. Por favor, desfaz? Deixa sem essa regra. 

Desculpe o transtorno.

Obrigado.

**Comment by gusfune** [comment]
Nem cheguei a subir, apenas removendo aqui do source o que tava pronto pra subir.
