### ISSUE TITLE
Usabilidade do menu

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#102]
O menu cinza desaparece no on mouse over.

[t_video5172770409854009348.mp4.zip](https://github.com/olugar/olugar/files/945254/t_video5172770409854009348.mp4.zip)

**Comment by gusfune** [comment]
O quão "urgente" é esse item?
Eu já achei o problema, mas to procurando uma solução que não envolva refazer o menu, tudo por conta de um gap pequeno na estrutura dos elementos.

**Comment by eduardoamuri** [comment]
Cara, fica bem chatinho de usar por conta disso. 

Podemos pensar em matar até semana que vem?

Obrigado.

**Comment by gusfune** [comment]
Claro, ta na fila aqui. Já passo um feedback assim que fechar.
Abs,

**Comment by gusfune** [comment]
Correção já ta no beta pra validação.
