### ISSUE TITLE
Adaptação para Mobile na tela Participe

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#11]
https://olugar.org/participe/

**Comment by gustavogitti** [comment]
Apaguei as que não estava sendo utilizadas, Gus. As outras estão OK.

O conteúdo da /participe está aqui:

https://olugar.org/wp-admin/post.php?post=55107&action=edit

**Comment by gusfune** [comment]
Achei, pronto e corrigido pra subir de vez!

**Comment by eduardoamuri** [comment]
Esse ainda não ficou bom, Gus.

O texto está jogado para a esquerda e não está ocupando a coluna toda, veja no anexo.

![whatsapp image 2016-08-31 at 10 14 42 am](https://cloud.githubusercontent.com/assets/247457/18130057/e5eb5a64-6f63-11e6-8569-f022778492ad.jpeg)

**Comment by gusfune** [comment]
Corrigido, subindo em prod direto.
