### ISSUE TITLE
"Manter logado" ativo como default

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#111]
Quando a pessoa vai se logar, o "manter logado" está desativado por default. Coloque ativo por default, por favor.
![screen shot 2017-04-26 at 16 54 02](https://cloud.githubusercontent.com/assets/21227612/25453879/fb5cdd20-2aa0-11e7-8dd9-35ff58ae32e9.png)

**Comment by gusfune** [comment]
Subi o fix no beta, pode validar? Também coloquei um placeholder pra senha.

**Comment by eduardoamuri** [comment]
Validado.
