### ISSUE TITLE
Posição de um campo no cadastro

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#112]
Gus, é só alinhar a data de nascimento:

![screen shot 2017-04-26 at 16 26 10](https://cloud.githubusercontent.com/assets/21227612/25453933/25e2cde8-2aa1-11e7-9a1c-2afe01e373cc.png)

**Comment by gusfune** [comment]
Subi o fix no beta, pode validar?

**Comment by eduardoamuri** [comment]
Validado.
