### ISSUE TITLE
URGENTE - Checkout em produção

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#118]
Gus, a tela de checkout em live não está funcionando. 

Estranhei o fato de não termos tido assinatura nos últimos 6 dias e fui conferir:

![screen shot 2017-05-02 at 8 20 34 am](https://cloud.githubusercontent.com/assets/247457/25615933/55d0917a-2f10-11e7-97fb-a3ab088df11d.png)

Pode atacar isso hoje, por favor? 

Estamos com um baita problema de caixa, não podemos nos dar ao luxo de vacilos assim.

Existe alguma ferramenta de teste automatizada para Ruby, para que esse tipo de coisa não aconteça mais?

**Comment by eduardoamuri** [comment]
Aqui o link do pedido: https://olugar.org/wp-admin/post.php?post=347342&action=edit

**Comment by gusfune** [comment]
Resolvido!
