### ISSUE TITLE
Ajuste de CSS em Blockquote

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#12]
No blockquote, deixar sem a margin esquerda de 40px, como no screenshot.
![screen_shot_2016-08-03_at_11 34 33_am](https://cloud.githubusercontent.com/assets/1147240/17953767/8158ca76-6a4c-11e6-85d0-6e892f664ff7.png)

**Comment by eduardoamuri** [comment]
Erro persiste por aqui, Gus.

**Comment by gusfune** [comment]
Agora sim corrigido, tinha feito justamente o inverso.

**Comment by eduardoamuri** [comment]
Está ok, pode subir para PRD. :)

**Comment by gustavogitti** [comment]
Corrigido no beta, pode subir!
