### ISSUE TITLE
Botar pixel code do Facebook

### ISSUE THREAD

**Issue by iodris** [olugar/olugar#13]
Na página de cadastro, imediatamente após a pessoa pagar.

**Comment by gusfune** [comment]
Qual o código do Pixel Code? Tem isso pronto?
Preciso ver se o S2Member permite alterar essa página, mas me passa o código pra já ver como isso é inserido.

**Comment by eduardoamuri** [comment]
@iodris , ajuda a gente com isso?

**Comment by iodris** [comment]
é isso?

***

Como faço para instalar um pixel de conversão:

https://www.facebook.com/business/help/373979379354234

***
Código:


<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '1120630904666765');
fbq('track', 'CompleteRegistration');</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1120630904666765&ev=PageView&noscript=1"
/></noscript>

**Comment by iodris** [comment]
O código não aparece no post, mandei por email, Gus.

**Comment by eduardoamuri** [comment]
Gus, precisa de algo aqui, para conseguirmos tocar esse item?

**Comment by gusfune** [comment]
Preciso sim @eduardoamuri. A tela de confirmação de compra do S2Member é dinâmica, aparentemente me parece inviável sem ter que mexer a fundo no plugin. Eu botaria em standby esse item até a gente decidir se muda ou não o sistema de membros. Realmente ta complicado agora.

**Comment by eduardoamuri** [comment]
Vamos tocar isso direto com o WooCommerce. Colocando em standby.

**Comment by gusfune** [comment]
Com o WooCommerce ficou fácil colocar. Já ta inserido!
