### ISSUE TITLE
Tópicos recentes são exibidos para não-membros

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#14]
Isso é mais uma dúvida pra verificar se é uma issue ou não.
Hoje o forum e qualquer tópico ta fechado o acesso pra não-membros, porém, a lista de tópicos recentes é aberta se tentar acessar deslogado: https://olugar.org/recentes/

Ele não permite o acesso a fóruns ou a nada, mas exibe a lista, isso deve ser exibido ou é de fato uma falha e devemos bloquear? Me confirma isso @gustavogitti ou @eduardoamuri?

**Comment by eduardoamuri** [comment]
É uma falha e devemos bloquear.

**Comment by gusfune** [comment]
Consegui bloquear, resolvido problema.
