### ISSUE TITLE
Mexer no editor de mensagem no fórum

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#16]
Gus, no fim de cada tópico do fórum, no editor de mensagens, veja se consegue, por favor:

Remover os botões: del, ul, ol, li, code, fechar tags.

Renomear "b-quote" para "citar".

Incluir um botão de recuo, igual existe no Gmail (criando espaço à esquerda, pode ser de 40px).

Mover o botão "adicionar mídia" para ficar na mesma linha dos outros botões, reduzindo espaço.

Obrigado!

**Comment by gusfune** [comment]
@gustavogitti ao invés de customizar o editor, acha melhor a gente mudar e colocar um editor visual? (igual o de posts do WP).
Acho que dessa forma ficaria melhor e facilitaria bastante o uso pros usuários. Me confirma pra poder seguir e ajustar.

**Comment by eduardoamuri** [comment]
Gus, precisamos de uma amostra disso no beta, e de um custo aproximado, em horas. :)

**Comment by gusfune** [comment]
Isso deve levar aproximadamente 1-2h pra implementar no beta @eduardoamuri. Depois disso tendo ok a gente coloca no ar.
Me da o ok pra eu poder seguir aqui em frente.

**Comment by gusfune** [comment]
Pessoal, posso seguir em frente com o ajuste ou fechamos ele? Preciso de um retorno.

**Comment by gustavogitti** [comment]
Pode seguir!

**Comment by gusfune** [comment]
Consegui implementar aqui mais rápido do que imaginava.
@gustavogitti, pode dar uma conferida no BETA?
Link: https://beta.olugar.org/recentes/
Ta liberado o mesmo editor do WP. Se precisar a gente habilita ou esconde itens que forem pertinentes. Com ok, subo em produção.

**Comment by gusfune** [comment]
Já ta no ar direto.

**Comment by gustavogitti** [comment]
Gus, está dando problema desde que você mexeu. Se não entender o que é, tenta deixar o editor texto (não visual) como default pra pessoa.

Olha esse tópico:

https://olugar.org/forums/topic/agir-em-vez-de-reagir/#post-63917

<!– [if gte mso 9]><xml>
<o:OfficeDocumentSettings>
<o:AllowPNG/>
</o:OfficeDocumentSettings>
</xml><![endif]–>
<p class=”MsoNormal” style=”margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”>Bom dia!</p>
<p class=”MsoNormal” style=”margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”></p>
<p class=”MsoNormal” style=”margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”><span style=”font-size: 12.0pt; line-height: 150%; font-family: ‘Arial’,’sans-serif’; mso-fareast-font-family: ‘Times New Roman’; mso-fareast-language: PT-BR;”>Comecei a exercitar o agir ao invés de reagir aqui no trabalho e tem sido bem difícil. Há algum tempo colegas de trabalho criaram um grupo no <i style=”mso-bidi-font-style: normal;”>whatsapp</i>, com o objetivo de solicitar trocas de horário, já que trabalhamos em horário de turno e de discutir questões como acordo coletivo, atitudes abusivas da gerencia, etc. Mas o espaço também se tornou um local para publicação de piadas, muitas delas de cunho homofóbico, machista, político, religioso, etc (indústria, com predominância de homens no local de trabalho).</span></p>
<p class=”MsoNormal” style=”margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”><span style=”font-size: 12.0pt; line-height: 150%; font-family: ‘Arial’,’sans-serif’; mso-fareast-font-family: ‘Times New Roman’; mso-fareast-language: PT-BR;”>Ultimamente sempre reagia a essas piadas, mandando algum texto sobre intolerância e preconceito logo na sequencia que alguém as publicava, com algum comentário raivoso. </span></p>
<p class=”MsoNormal” style=”margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”><span style=”font-size: 12.0pt; line-height: 150%; font-family: ‘Arial’,’sans-serif’; mso-fareast-font-family: ‘Times New Roman’; mso-fareast-language: PT-BR;”>Vinha reagindo desta forma há algum tempo, e as piadas continuavam, as criticas que fazia só em uma ocasião foi levantando comentário: logo após uma piada homofóbica, mandei um texto falando de 12 atitudes que machucam e matam LGBTs, e o único comentário feito foi sobre um erro de português no texto (ao menos alguém leu), nada sobre o assunto em questão.</span></p>
<p class=”MsoNormal” style=”margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”><span style=”font-size: 12.0pt; line-height: 150%; font-family: ‘Arial’,’sans-serif’; mso-fareast-font-family: ‘Times New Roman’; mso-fareast-language: PT-BR;”>Por fim na última semana, depois de já ter começado a exercitar o agir em vez de reagir, publicaram um texto pejorativo sobre bairros da região norte da cidade, local onde cresci e ainda moro, após, eu<span style=”mso-spacerun: yes;”>  </span>enviar mais um texto sobre intolerância e um comentário raivoso, parei e pensei, pois, essa reação repetida só tem me causado desconforto e irritação e que o grupo permanece mandando os mesmos tipos de piada. Então simplesmente sai do grupo, já que após parar e pensar um pouco percebi que se o conteúdo não agrega, para que vou insistir em recebê-lo e debate-lo em vão.</span></p>
<p class=”MsoNormal” style=”margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”><span style=”font-size: 12.0pt; line-height: 150%; font-family: ‘Arial’,’sans-serif’; mso-fareast-font-family: ‘Times New Roman’; mso-fareast-language: PT-BR;”>Ao sair do grupo, o colega que publicou a piada pejorativa sobre os bairros, mandou uma mensagem me<span style=”mso-spacerun: yes;”>  </span>questionando pelo fato de eu ter saído do grupo por uma besteira, então respondi, que já vinha me irritando há algum tempo com aquele tipo de piada no grupo e que não considerava besteira. Ele então me perguntou se alguma vez me ofendeu com alguma brincadeira, então, desabafei que em várias ocasiões, e que eu só nunca havia falado isso com ele porque eu não me aceitava bem, então não conseguia expressar o que sentia quando ele fazia uma piada homofóbica, e que eu me mantinha neutro por fora, mas me torturando por dentro. Ele se desculpou, falando que nunca foi a intenção dele, e eu falei para que ele passasse a pensar antes de fazer comentários pejorativos, porque não há como saber quem ali presente está sendo machucado por aquele comentário e não tem forças para expor, para se defender, se proteger de tal comentário.</span></p>

<!– [if gte mso 9]><xml>
<o:OfficeDocumentSettings>
<o:AllowPNG/>
</o:OfficeDocumentSettings>
</xml><![endif]–> 
<p class=”MsoNormal” style=”mso-margin-top-alt: auto; margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”><span style=”font-size: 12.0pt; line-height: 150%; font-family: ‘Arial’,’sans-serif’; mso-fareast-font-family: ‘Times New Roman’; mso-fareast-language: PT-BR;”>Não está sendo fácil tentar agir em vez de reagir, mas o esforço para implementar a prática tem me ajudado a parar e pensar antes de tomar uma decisão de forma explosiva, mesmo que a reação seja contra alguma injustiça, pois, responder uma injustiça com outra, não agrega em nada.</span></p>
 
<p class=”MsoNormal” style=”mso-margin-top-alt: auto; margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”><span style=”font-size: 12.0pt; line-height: 150%; font-family: ‘Arial’,’sans-serif’; mso-fareast-font-family: ‘Times New Roman’; mso-fareast-language: PT-BR;”>Abraços.</span></p>
 
<p class=”MsoNormal” style=”mso-margin-top-alt: auto; margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: 150%;”><span style=”font-size: 12.0pt; line-height: 150%; font-family: ‘Arial’,’sans-serif’; mso-fareast-font-family: ‘Times New Roman’; mso-fareast-language: PT-BR;”>Júlio.</span></p>
 

<!– [if gte mso 9]><xml>
<w:WordDocument>
<w:View>Normal</w:View>
<w:Zoom>0</w:Zoom>
<w:TrackMoves/>
<w:TrackFormatting/>
<w:HyphenationZone>21</w:HyphenationZone>
<w:PunctuationKerning/>
<w:ValidateAgainstSchemas/>
<w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
<w:IgnoreMixedContent>false</w:IgnoreMixedContent>
<w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
<w:DoNotPromoteQF/>
<w:LidThemeOther>PT-BR</w:LidThemeOther>
<w:LidThemeAsian>X-NONE</w:LidThemeAsian>
<w:LidThemeComplexScript>X-NONE</w:LidThemeComplexScript>
<w:Compatibility>
<w:BreakWrappedTables/>
<w:SnapToGridInCell/>
<w:WrapTextWithPunct/>
<w:UseAsianBreakRules/>
<w:DontGrowAutofit/>
<w:SplitPgBreakAndParaMark/>
<w:EnableOpenTypeKerning/>
<w:DontFlipMirrorIndents/>
<w:OverrideTableStyleHps/>
</w:Compatibility>
<m:mathPr>
<m:mathFont m:val=”Cambria Math”/>
<m:brkBin m:val=”before”/>
<m:brkBinSub m:val=”--“/>
<m:smallFrac m:val=”off”/>
<m:dispDef/>
<m:lMargin m:val=”0″/>
<m:rMargin m:val=”0″/>
<m:defJc m:val=”centerGroup”/>
<m:wrapIndent m:val=”1440″/>
<m:intLim m:val=”subSup”/>
<m:naryLim m:val=”undOvr”/>
</m:mathPr></w:WordDocument>
</xml><![endif]–><!– [if gte mso 9]><xml>
<w:LatentStyles DefLockedState=”false” DefUnhideWhenUsed=”true”
DefSemiHidden=”true” DefQFormat=”false” DefPriority=”99″
LatentStyleCount=”267″>
<w:LsdException Locked=”false” Priority=”0″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Normal”/>
<w:LsdException Locked=”false” Priority=”9″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”heading 1″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 2″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 3″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 4″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 5″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 6″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 7″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 8″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 9″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 1″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 2″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 3″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 4″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 5″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 6″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 7″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 8″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 9″/>
<w:LsdException Locked=”false” Priority=”35″ QFormat=”true” Name=”caption”/>
<w:LsdException Locked=”false” Priority=”10″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Title”/>
<w:LsdException Locked=”false” Priority=”1″ Name=”Default Paragraph Font”/>
<w:LsdException Locked=”false” Priority=”11″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Subtitle”/>
<w:LsdException Locked=”false” Priority=”22″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Strong”/>
<w:LsdException Locked=”false” Priority=”20″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Emphasis”/>
<w:LsdException Locked=”false” Priority=”59″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Table Grid”/>
<w:LsdException Locked=”false” UnhideWhenUsed=”false” Name=”Placeholder Text”/>
<w:LsdException Locked=”false” Priority=”1″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”No Spacing”/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading”/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List”/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid”/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List”/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading”/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List”/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid”/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 1″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 1″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 1″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 1″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 1″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 1″/>
<w:LsdException Locked=”false” UnhideWhenUsed=”false” Name=”Revision”/>
<w:LsdException Locked=”false” Priority=”34″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”List Paragraph”/>
<w:LsdException Locked=”false” Priority=”29″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Quote”/>
<w:LsdException Locked=”false” Priority=”30″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Intense Quote”/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 1″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 1″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 1″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 1″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 1″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 1″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 1″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 1″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 2″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 2″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 2″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 2″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 2″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 2″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 2″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 2″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 2″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 2″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 2″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 2″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 2″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 2″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 3″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 3″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 3″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 3″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 3″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 3″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 3″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 3″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 3″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 3″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 3″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 3″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 3″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 3″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 4″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 4″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 4″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 4″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 4″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 4″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 4″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 4″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 4″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 4″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 4″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 4″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 4″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 4″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 5″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 5″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 5″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 5″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 5″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 5″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 5″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 5″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 5″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 5″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 5″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 5″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 5″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 5″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 6″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 6″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 6″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 6″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 6″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 6″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 6″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 6″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 6″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 6″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 6″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 6″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 6″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 6″/>
<w:LsdException Locked=”false” Priority=”19″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Subtle Emphasis”/>
<w:LsdException Locked=”false” Priority=”21″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Intense Emphasis”/>
<w:LsdException Locked=”false” Priority=”31″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Subtle Reference”/>
<w:LsdException Locked=”false” Priority=”32″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Intense Reference”/>
<w:LsdException Locked=”false” Priority=”33″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Book Title”/>
<w:LsdException Locked=”false” Priority=”37″ Name=”Bibliography”/>
<w:LsdException Locked=”false” Priority=”39″ QFormat=”true” Name=”TOC Heading”/>
</w:LatentStyles>
</xml><![endif]–><!– [if gte mso 10]>
<style>
/* Style Definitions */
table.MsoNormalTable
{mso-style-name:”Tabela normal”;
mso-tstyle-rowband-size:0;
mso-tstyle-colband-size:0;
mso-style-noshow:yes;
mso-style-priority:99;
mso-style-parent:””;
mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
mso-para-margin-top:0cm;
mso-para-margin-right:0cm;
mso-para-margin-bottom:10.0pt;
mso-para-margin-left:0cm;
line-height:115%;
mso-pagination:widow-orphan;
font-size:11.0pt;
font-family:”Calibri”,”sans-serif”;
mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;
mso-hansi-font-family:Calibri;
mso-hansi-theme-font:minor-latin;
mso-fareast-language:EN-US;}
</style>
<![endif]–>
