### ISSUE TITLE
Indicador de que o usuário está ativo

### ISSUE THREAD

**Issue by iodris** [olugar/olugar#17]
No perfil rápido que aparece no lado esquerdo no fórum: tirar o IP e colocar um "ativo há x tempo".

Hoje está assim:

![captura de tela 2016-09-21 as 09 59 09](https://cloud.githubusercontent.com/assets/21367393/18711360/f54e4cdc-7fdf-11e6-905d-4978d48c4d6c.png)

É pra ficar assim:

![2](https://cloud.githubusercontent.com/assets/21367393/18712806/62354534-7fe6-11e6-90e3-84ee1b418c35.png)

Esse "ativo há x minutos" é como o que está no https://olugar.org/pessoas/

**Comment by gusfune** [comment]
@iodris: o IP já foi removido automaticamente no update do Buddypress.
Essa funcionalidade de "ativo há x minutos atrás" é do Buddypress e ela "não conversa" com o BBpress. Dei uma fuçada no source em como tentar resolver mas seria basicamente refazer isso pra aparecer no fórum. 
Levaria umas 4h de trabalho, eu considero inviável visto que alteraria core do sistema e poderia cancelar em qualquer update, além de pesar muito no servidor. Vou deixar fechado por hora e retomamos isso num futuro breve quando o sistema estiver mais robusto, pode ser?
