### ISSUE TITLE
Exportar, de maneira recorrente, os assinantes ativos no paypal (através da API)

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#18]
Gus,

Queria muito receber toda segunda de manhã um export com os pagamentos recorrentes que temos no paypal. A API deles é fácil de mexer.

Não precisamos de informações de pagamentos específicos, precisamos da lista dos ativos (hoje eu consigo acessar a lista através da interface web, mas é uma porquice, só mostra 25 por vez).

Foto anexa.

![screen shot 2016-09-27 at 3 11 59 pm](https://cloud.githubusercontent.com/assets/247457/18886077/cdfa1aa0-84c4-11e6-9264-706f7a4e8016.png)
 
Conseguimos?

http://www.techrepublic.com/article/handling-recurring-payments-with-paypal-subscriptions-and-ipn/5331883/

**Comment by gusfune** [comment]
Como falamos, pela API do PayPal não da.
Pelo Wordpress, da pra fazer pelo plugin de export de membros:
https://olugar.org/wp-admin/users.php?page=export-user-data

Basta selecionar **stored options**, seleciona **assinantes**, aperta load e depois roda o export.
