### ISSUE TITLE
Implementar autenticação no nosso servidor / Mailchimp

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#19]
Gus, acho que isso pode ajudar os emails chegarem, o que acha?

http://kb.mailchimp.com/accounts/email-authentication/set-up-custom-domain-authentication-dkim-and-spf

Abraço,

Gustavo

**Comment by gusfune** [comment]
Mas qual o problema que ta rolando de sincronização @gustavogitti? Vc me ta brifando uma solução, mas não explicou o problema.

**Comment by eduardoamuri** [comment]
Explicando: grande parte dos nossos e-mails ou vão para a caixa de spam da pessoa, ou vão para a aba Promotion. 

Segundo a KB do próprio Mailchimp, o swap (interno) de domínio pode ajudar a fazer o e-mail chegar direto na inbox (teoricamente, as chances aumentam). 

Queria entender o custo disso em horas, por favor, Gus.

**Comment by gusfune** [comment]
Tranquilo de fazer, levou pouco menos de 5 minutos. Já ta autenticando direto. Abre outro issue se persistir o problema ou precisar de algo mais nesse sentido.
