### ISSUE TITLE
Falha no sync entre Wordpress e Mailchimp

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#20]
Gus, hoje percebi que essa pessoa entrou em setembro e o Wordpress não sincronizou com o Mailchimp:

fabiano0808@gmail.com

Você pode ver no log porque não rolou? Vou fazer na mão agora.

Além disso, agora que tô vendo que o plugin não foi atualizado! Você atualiza?

https://olugar.org/wp-admin/admin.php?page=mailchimp-for-wp-sync

Abraço!

**Comment by gusfune** [comment]
Atualizei o plugin, da uma olhada nos erros do debug log: https://olugar.org/wp-admin/admin.php?page=mailchimp-for-wp-other
O problema com quem não sincroniza é quem não preencheu sobrenome e/ou estado, todos os erros estão nesses perfis incompletos. Basta ver quem falta e corrigir pra ficar de acordo.
