### ISSUE TITLE
Cadastros indo pro "pending activation"

### ISSUE THREAD

**Issue by iodris** [olugar/olugar#21]
Essa semana aconteceu com 4 usuários.

O último, no dia 10, foi com a "apaula" (apchaves@yahoo.com)

Dá pra ver o que tá rolando?

**Comment by gusfune** [comment]
O que é pending activation?

**Comment by iodris** [comment]
A pessoa paga, mas o WP não ativa o cadastro dela, ela não recebe o email etc. Fica como cadastro pendente, aí tem de ir em configirações > buddypress > pending activation e ativar manualmente. Acho que todos eles tão caindo lá.

![captura de tela 2016-10-14 as 11 01 17](https://cloud.githubusercontent.com/assets/21367393/19389882/18078de6-91fc-11e6-804f-b55178a09bd0.png)

**Comment by gustavogitti** [comment]
Gus, elas não estão recebendo esse email aqui: 

Original Message

Message ID	<dGB4E_ikQ0qdT4e90j_dag@ismtpd0005p1iad1.sendgrid.net>
Created at:	Thu, Jan 7, 2016 at 4:10 PM (Delivered after 4 seconds)
From:	o lugar <coordenacao@olugar.org>
To:	gustavo.gitti@gmail.com
Subject:	[o lugar] Ative seu cadastro
SPF:	PASS with IP 167.89.16.17 Learn more
DKIM:	PASS with domain olugar.org Learn more


Download Original	Copy to clipboard	
Delivered-To: gustavo.gitti@gmail.com
Received: by 10.129.146.129 with SMTP id j123csp75081ywg;
        Thu, 7 Jan 2016 10:10:34 -0800 (PST)
X-Received: by 10.202.85.7 with SMTP id j7mr74066831oib.11.1452190234620;
        Thu, 07 Jan 2016 10:10:34 -0800 (PST)
Return-Path: <bounces+2031940-56b8-gustavo.gitti=gmail.com@mail.olugar.org>
Received: from o1678916x17.outbound-mail.sendgrid.net (o1678916x17.outbound-mail.sendgrid.net. [167.89.16.17])
        by mx.google.com with ESMTPS id a8si8361292obt.51.2016.01.07.10.10.34
        for <gustavo.gitti@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 07 Jan 2016 10:10:34 -0800 (PST)
Received-SPF: pass (google.com: domain of bounces+2031940-56b8-gustavo.gitti=gmail.com@mail.olugar.org designates 167.89.16.17 as permitted sender) client-ip=167.89.16.17;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of bounces+2031940-56b8-gustavo.gitti=gmail.com@mail.olugar.org designates 167.89.16.17 as permitted sender) smtp.mailfrom=bounces+2031940-56b8-gustavo.gitti=gmail.com@mail.olugar.org;
       dkim=pass header.i=@olugar.org;
       dkim=pass header.i=@sendgrid.info
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=olugar.org; h=from:mime-version:reply-to:subject:to:content-type; s=m1; bh=V7NKlbYm3A9eCH9HPF9B0GjK5wM=; b=Ws9pebSG5cLuea3RtCHjCCoICc/ji Mn7dRUVi773dy9J2oZXmNY7TbnET3vljvcEy9IRGT0JynWc2m8SuBkuS3dxk+ODc zau8VQAQKfFYkNqvHZx+OUhJN4lp4rwqOQdCj0ud6WcwiXc4ngOoDITRLR+gYvu5 8ow1o56/mK/U3U=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=sendgrid.info; h=from:mime-version:reply-to:subject:to:content-type:x-feedback-id; s=smtpapi; bh=V7NKlbYm3A9eCH9HPF9B0GjK5wM=; b=zHcZIA25mPXRkbciJM BLl5rSlbEIxP8Ry7fQwUYmx+jJuOy7GcJAmRx4zQiH/hbF+XVb0UcUzOxzJB6G+w 9G0UDC39nIsP6QRnL2yOKYSjxNKhnCaOciMYwGCZMvTol2ugXSLwHMriduuMjlZx pQGFs0qX0nNwBE3Ly8uzDMv14=
Received: by filter0628p1mdw1.sendgrid.net with SMTP id filter0628p1mdw1.27602.568EAA169B
        2016-01-07 18:10:30.88889444 +0000 UTC
Received: from MjAzMTk0MA (olugar.org [172.99.67.165]) by ismtpd0005p1iad1.sendgrid.net (SG) with HTTP id dGB4E_ikQ0qdT4e90j_dag for <gustavo.gitti@gmail.com>; Thu, 07 Jan 2016 18:10:30.990 +0000 (UTC)
Date: Thu, 07 Jan 2016 18:10:30 +0000
From: o lugar <coordenacao@olugar.org>
Mime-Version: 1.0
Reply-To: contato@olugar.org
Subject: [o lugar] Ative seu cadastro
To: gustavo.gitti@gmail.com
Message-ID: <dGB4E_ikQ0qdT4e90j_dag@ismtpd0005p1iad1.sendgrid.net>
Content-type: multipart/alternative; boundary="----------=_1452190232-14783-173"
X-SG-EID: kXJYDHEeHvDmXkvde2DdvKJ9fHakE3PTzlw9g1XHwHsoX7dz4IpxSI5uKVzYs5WgxERQF+OF7hY/7+ KliqoWsgbhh9UDDZ7AtqImEDaCmWHAtabzYxn1P6fyJL3M2PHuT3oyEmpwdfAh0y9l9xpat1ji7TaN hIGfJ/3MexMaRF1bujhy2qDpwoWQhXaXqPGdufe4lgI9GpLrNK6kDPlKjaQTJyvawriPIPN5oBXcmi k=
X-SG-ID: 8jXKzZkZOLw8fDcfQreIJqrM1Y7jV9V6APmE/W7b4l8LQdN1CsYcxNV15PWnDqpz
X-Feedback-ID: 2031940:cZDURPxsmHFt5hYaw7NpM0tWd/n6Sbe/3SbUr1JTVVM=:Rlvcarf9nK3UqQGLjzcYaO4q0HSk+4HiXEHSakq3jUw=:SG

------------=_1452190232-14783-173
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8

Para ativar seu cadastro no lugar por favor clique agora neste link:

http://link.olugar.org/wf/click?upn=3Dc0WRHgS7Hah40pBZo89yUdMK2Dq0xlqJRSVFJ=
RKPXctten6HBjTHG2zRl16WaxsLXpD7ubR4ztp6mlPIOVT7AlBKBHIGDy1F-2BXAelj32AUo-3D=
_2RHgJn6wQSaWU0IcIrNC6mH7jgc0DB9a6YRkJkQcxw1ti08da4rwCs-2FH-2FVNNpt-2Fydotk=
p57Pvx2BTBUptu6Yc5L7UQGHSuN8cjAvAFjLad1Et6kem9zhK8s4SMoY2KDKcRQZbg610FVJK-2=
F457ZufbEroK8a-2BUwofi-2BS-2BtG-2F3EWUKw0AiW-2FfmLv4pckPSf8BrYfQKrMRQ9C2ESZ=
kVEXrXb6zfIgizIjJl8LshH3ds7rzduB9Mho-2Biolw26CYRuxTqhFQM6Qle3eQr9Pyldd9VBQ-=
3D-3D

A seguir, entre com seus dados de acesso e leia a p=C3=A1gina de boas vinda=
s:

http://link.olugar.org/wf/click?upn=3Dc0WRHgS7Hah40pBZo89yUakjGrN-2FVyG97r-=
2FxYPnjhEqbKz4yN8AwKP3KKkyHjN4l_2RHgJn6wQSaWU0IcIrNC6mH7jgc0DB9a6YRkJkQcxw1=
ti08da4rwCs-2FH-2FVNNpt-2Fydotkp57Pvx2BTBUptu6YcyhEl7AKDUKdh9AXxLtCoQTltu4s=
vYAky1m3wr36oG6qQacFqvHFnjnhBuFkaaeA1HZeIu08iiKq40f0vn8E5EsmPWAczcbMwiKBPd4=
Te3Luob46XsToaSZzqDCdy0OYlapLrjgsxAhZw8ekCb0IKcQ-2BkZQdeyJ7KqyT76B42C6d4Xe3=
uJvs98G7Dh1WilsWGA-3D-3D

=E2=80=A6

Seguimos!

Abra=C3=A7o,

Gustavo Gitti
F=C3=A1bio Rodrigues
coordenacao@olugar.org


------------=_1452190232-14783-173
Content-Type: text/html; charset="UTF-8"
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

<html><body>
<p>Para ativar seu cadastro no lugar por favor clique agora neste link:</p>
<p><a href=3D"http://link.olugar.org/wf/click?upn=3Dc0WRHgS7Hah40pBZo89yUdM=
K2Dq0xlqJRSVFJRKPXctten6HBjTHG2zRl16WaxsLXpD7ubR4ztp6mlPIOVT7AlBKBHIGDy1F-2=
BXAelj32AUo-3D_2RHgJn6wQSaWU0IcIrNC6mH7jgc0DB9a6YRkJkQcxw1ti08da4rwCs-2FH-2=
FVNNpt-2FyDutl-2FlSa7HTtw82q0VkQmF3-2F6wZgmHAMY9-2BamHiXk-2BJNAr2YHqzQB9QG5=
0YeHjcQ8uCj0HQK9jtiz8p75dmeWqbtfD0NN1isnXkB4LpDwSDLJxm3NQEEjUmuS-2Fs5cmj8U4=
ao0jCVXUDj3TH7NFgIV0wxjU3WYXMbJLU0uP3AbdKLqGnxFwoIW6dHi4Fef-2B340ghbtj4hoNL=
w6IyVJiykxw-3D-3D">http://olugar.org/ative-seu-cadastro/aa2285ef1557d9c4ebc=
d0f840d10e1cc/</a></p>
<p>A seguir, entre com seus dados de acesso e leia a p=C3=A1gina de boas vi=
ndas:</p>
<p><a href=3D"http://link.olugar.org/wf/click?upn=3Dc0WRHgS7Hah40pBZo89yUak=
jGrN-2FVyG97r-2FxYPnjhEqbKz4yN8AwKP3KKkyHjN4l_2RHgJn6wQSaWU0IcIrNC6mH7jgc0D=
B9a6YRkJkQcxw1ti08da4rwCs-2FH-2FVNNpt-2FyDutl-2FlSa7HTtw82q0VkQmIeH68a1ZbU-=
2BlTylURsS1ydQcGWG8kg-2FxrpMpnWeo6JedaiterdxokskM-2Fr8fWjuBPtqaO-2BwvdAsnl6=
VP9kB-2BA-2FmwGHFyZZenxUfCzs2ujaOXLSPP-2FGv1GaTzlfI8WBkPi-2Bf81ie7u-2F-2Fud=
Xh0UMt-2F-2BmMI0GqVl8i5MmkgeJxHWS-2BU-2FBgNDaxUJpfb5JozQh74A-3D-3D">http://=
olugar.org/bem-vindo/</a></p>
<p>=E2=80=A6</p>
<p>Seguimos!</p>
<p>Abra=C3=A7o,</p>
<p>Gustavo Gitti F=C3=A1bio Rodrigues coordenacao@olugar.org</p>

<img src=3D"http://link.olugar.org/wf/open?upn=3D2RHgJn6wQSaWU0IcIrNC6mH7jg=
c0DB9a6YRkJkQcxw1ti08da4rwCs-2FH-2FVNNpt-2FyJVN0pbylv2XC-2F67VlTADte2ekDR7a=
ba4Us0oil5OTR30S-2F1B9Y6kQxydMyZvNCQLIDzI-2FstsrFN-2BLcggxUeZYSAPIu10eFNahZ=
rfF2x6bVkVEvhsxRuvSLnExWS-2Bm-2FVWc2vGmSSTGpQ2-2FTqLfeJ5a0ez4u-2Fd2IAR4c-2F=
IS-2BzXZwV6XPvT5jf-2BaeUkAKZrJxSaExfXIc6tA-2FaUqfcB8XVSwg-3D-3D" alt=3D"" w=
idth=3D"1" height=3D"1" border=3D"0" style=3D"height:1px !important;width:1=
px !important;border-width:0 !important;margin-top:0 !important;margin-bott=
om:0 !important;margin-right:0 !important;margin-left:0 !important;padding-=
top:0 !important;padding-bottom:0 !important;padding-right:0 !important;pad=
ding-left:0 !important;"/>
</body></html>

------------=_1452190232-14783-173--

**Comment by gustavogitti** [comment]
Gus, ainda está acontecendo e com quase todo mundo! Você consegue ver com urgência. Isso é dor de cabeça.

**Comment by gusfune** [comment]
Acabei de achar o problema @gustavogitti e @iodris.
O serviço que cuida do envio de emails, Sendgrid, suspendeu a conta do Lugar por conta de "falta de pagamento" em um invoice de $1 de Outubro.
Eu acionei o suporte e pedi pra eles tentarem cobrar de novo do cartão de crédito. Se não tiver sucesso, vou pedir pra um de vocês acessar a conta e atualizar o cartão. Isso vai resolver o problema do envio dos emails de vez.
**Outro detalhe**: me encaminhem qualquer email que eventualmente chegar deles até resolvermos isso.

**Comment by gustavogitti** [comment]
Gus, não tá rolando o login que está na tabela de senhas (amuri@olugar.org ou olugar e a senha 108bodisatvas...). Me passa por email por favor a senha.

**Comment by gusfune** [comment]
Enviado no Whatsapp!

**Comment by gusfune** [comment]
Resolvido com o Sendgrid de volta ao ar.
