### ISSUE TITLE
Emails do site não chegam

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#22]
Gus, as mensagens enviadas em /contato não estão chegando. E parei de receber há um tempo as mensagens dos fóruns / tópicos que assino. O que tá rolando com os emails do site???

Deve ser o mesmo problema que impede os emails de ativação de chegarem... Você mexeu em algo?

O Sendgrid é pago? Será que não tenho de trocar meu cartão lá?

Abraço!

**Comment by gusfune** [comment]
Isso ta ligado ao problema da issue #21.
Precisa trocar o cartão lá. Vamos esperar retorno do suporte, se não resolver, troca o cartão que a gente resolve os dois problemas deu ma vez.

**Comment by gusfune** [comment]
Resolvido junto da issue #21.
