### ISSUE TITLE
Sumiu o painel com a lista de participantes 

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#24]
Gus,

Lembra daquela página especial no admin do WP listando as pessoas que se apresentaram recentemente, sabe?

Ela sumiu.

Sabe o que aconteceu?

Abraço!

**Comment by gusfune** [comment]
Essa tela aparece no BETA? Sabe me dizer se era do Buddypress ou do S2Member?
Não me recordo da tela, me ajuda a pegar mais infos que eu localizo e recupero ela.

**Comment by gustavogitti** [comment]
Gus, aqui a URL direta:

https://olugar.org/wp-admin/admin.php?page=gasoline-dashboard

Por que sumiu?

Você investiga? Veja se tem no beta...

Abraço!

**Comment by gusfune** [comment]
Resolvido.
Plugin tava desativado, acho que eu desliguei sem querer.
