### ISSUE TITLE
[on hold] Email chegando desconfigurado

### ISSUE THREAD

**Issue by iodris** [olugar/olugar#25]
Gus, veja como estão chegando os emails que o WP envia:

![captura de tela 2016-11-01 as 16 00 55](https://cloud.githubusercontent.com/assets/21367393/19900343/4dd0e394-a04a-11e6-9d9d-149ab2d33505.png)

**Comment by gustavogitti** [comment]
Gus, viu isso?

**Comment by gusfune** [comment]
Dei uma olhada no problema @gustavogitti e @iodris e preciso de um help de vocês pra resolver isso de vez:
1. Tem como me encaminhar um email recente desses com problema? Um que encaminharam recente não tinham os códigos assim no meio pra verificar.
2. Podem criar um post no BETA do Lugar e me taguear para que eu receba direto uma notificação? No caso, utilizem o máximo de formatação que puderem para que eu receba possivelmente bugado.

Com isso já da pra achar o problema, parece que ta no BBPress direto, pois os emails padrões do Wordpress tão vindo ok, e o sendgrid ta enviando como HTML a formatação.

**Comment by eduardoamuri** [comment]
Gus,

O problema, na real, é com os e-mails que vem do BBPress, tipo esse aqui: 

![screen shot 2017-02-22 at 16 53 29](https://cloud.githubusercontent.com/assets/247457/23229680/e76467d2-f91f-11e6-9201-3844b095c78b.png)

Anexo o tracert do e-mail.

[original_msg.txt](https://github.com/olugar/olugar/files/794657/original_msg.txt)

Me avise se precisar de mais ajuda para descobrir de onde vem.

**Comment by gusfune** [comment]
Com a resolução da issue #30 esse problema ta rolando ainda ou permanece? Me confirma?

**Comment by eduardoamuri** [comment]
Colocando a issue em on hold, por enquanto.

**Comment by eduardoamuri** [comment]
Issue fechada, reabriremos caso o problema volte a acontecer.
