### ISSUE TITLE
Problema urgente no editor

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#26]
Gus, está dando problema desde que você mexeu. Se não entender o que é, tenta deixar o editor texto (não visual) como default pra pessoa.

@gusfune #16 

Olha esse tópico:

https://olugar.org/forums/topic/agir-em-vez-de-reagir/#post-63917

<!– [if gte mso 9]>
<o:OfficeDocumentSettings>
<o:AllowPNG/>
</o:OfficeDocumentSettings>
<![endif]–>

Bom dia!

Comecei a exercitar o agir ao invés de reagir aqui no trabalho e tem sido bem difícil. Há algum tempo colegas de trabalho criaram um grupo no whatsapp, com o objetivo de solicitar trocas de horário, já que trabalhamos em horário de turno e de discutir questões como acordo coletivo, atitudes abusivas da gerencia, etc. Mas o espaço também se tornou um local para publicação de piadas, muitas delas de cunho homofóbico, machista, político, religioso, etc (indústria, com predominância de homens no local de trabalho).

Ultimamente sempre reagia a essas piadas, mandando algum texto sobre intolerância e preconceito logo na sequencia que alguém as publicava, com algum comentário raivoso.

Vinha reagindo desta forma há algum tempo, e as piadas continuavam, as criticas que fazia só em uma ocasião foi levantando comentário: logo após uma piada homofóbica, mandei um texto falando de 12 atitudes que machucam e matam LGBTs, e o único comentário feito foi sobre um erro de português no texto (ao menos alguém leu), nada sobre o assunto em questão.

Por fim na última semana, depois de já ter começado a exercitar o agir em vez de reagir, publicaram um texto pejorativo sobre bairros da região norte da cidade, local onde cresci e ainda moro, após, eu enviar mais um texto sobre intolerância e um comentário raivoso, parei e pensei, pois, essa reação repetida só tem me causado desconforto e irritação e que o grupo permanece mandando os mesmos tipos de piada. Então simplesmente sai do grupo, já que após parar e pensar um pouco percebi que se o conteúdo não agrega, para que vou insistir em recebê-lo e debate-lo em vão.

Ao sair do grupo, o colega que publicou a piada pejorativa sobre os bairros, mandou uma mensagem me questionando pelo fato de eu ter saído do grupo por uma besteira, então respondi, que já vinha me irritando há algum tempo com aquele tipo de piada no grupo e que não considerava besteira. Ele então me perguntou se alguma vez me ofendeu com alguma brincadeira, então, desabafei que em várias ocasiões, e que eu só nunca havia falado isso com ele porque eu não me aceitava bem, então não conseguia expressar o que sentia quando ele fazia uma piada homofóbica, e que eu me mantinha neutro por fora, mas me torturando por dentro. Ele se desculpou, falando que nunca foi a intenção dele, e eu falei para que ele passasse a pensar antes de fazer comentários pejorativos, porque não há como saber quem ali presente está sendo machucado por aquele comentário e não tem forças para expor, para se defender, se proteger de tal comentário.

<!– [if gte mso 9]>
<o:OfficeDocumentSettings>
<o:AllowPNG/>
</o:OfficeDocumentSettings>
<![endif]–>

Não está sendo fácil tentar agir em vez de reagir, mas o esforço para implementar a prática tem me ajudado a parar e pensar antes de tomar uma decisão de forma explosiva, mesmo que a reação seja contra alguma injustiça, pois, responder uma injustiça com outra, não agrega em nada.

Abraços.

Júlio.

<!– [if gte mso 9]>
<w:WordDocument>
<w:View>Normal</w:View>
<w:Zoom>0</w:Zoom>
<w:TrackMoves/>
<w:TrackFormatting/>
<w:HyphenationZone>21</w:HyphenationZone>
<w:PunctuationKerning/>
<w:ValidateAgainstSchemas/>
<w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
<w:IgnoreMixedContent>false</w:IgnoreMixedContent>
<w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
<w:DoNotPromoteQF/>
<w:LidThemeOther>PT-BR</w:LidThemeOther>
<w:LidThemeAsian>X-NONE</w:LidThemeAsian>
<w:LidThemeComplexScript>X-NONE</w:LidThemeComplexScript>
<w:Compatibility>
<w:BreakWrappedTables/>
<w:SnapToGridInCell/>
<w:WrapTextWithPunct/>
<w:UseAsianBreakRules/>
<w:DontGrowAutofit/>
<w:SplitPgBreakAndParaMark/>
<w:EnableOpenTypeKerning/>
<w:DontFlipMirrorIndents/>
<w:OverrideTableStyleHps/>
</w:Compatibility>
<m:mathPr>
<m:mathFont m:val=”Cambria Math”/>
<m:brkBin m:val=”before”/>
<m:brkBinSub m:val=”--“/>
<m:smallFrac m:val=”off”/>
<m:dispDef/>
<m:lMargin m:val=”0″/>
<m:rMargin m:val=”0″/>
<m:defJc m:val=”centerGroup”/>
<m:wrapIndent m:val=”1440″/>
<m:intLim m:val=”subSup”/>
<m:naryLim m:val=”undOvr”/>
</m:mathPr></w:WordDocument>
<![endif]–><!– [if gte mso 9]>
<w:LatentStyles DefLockedState=”false” DefUnhideWhenUsed=”true”
DefSemiHidden=”true” DefQFormat=”false” DefPriority=”99″
LatentStyleCount=”267″>
<w:LsdException Locked=”false” Priority=”0″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Normal”/>
<w:LsdException Locked=”false” Priority=”9″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”heading 1″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 2″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 3″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 4″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 5″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 6″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 7″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 8″/>
<w:LsdException Locked=”false” Priority=”9″ QFormat=”true” Name=”heading 9″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 1″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 2″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 3″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 4″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 5″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 6″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 7″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 8″/>
<w:LsdException Locked=”false” Priority=”39″ Name=”toc 9″/>
<w:LsdException Locked=”false” Priority=”35″ QFormat=”true” Name=”caption”/>
<w:LsdException Locked=”false” Priority=”10″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Title”/>
<w:LsdException Locked=”false” Priority=”1″ Name=”Default Paragraph Font”/>
<w:LsdException Locked=”false” Priority=”11″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Subtitle”/>
<w:LsdException Locked=”false” Priority=”22″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Strong”/>
<w:LsdException Locked=”false” Priority=”20″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Emphasis”/>
<w:LsdException Locked=”false” Priority=”59″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Table Grid”/>
<w:LsdException Locked=”false” UnhideWhenUsed=”false” Name=”Placeholder Text”/>
<w:LsdException Locked=”false” Priority=”1″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”No Spacing”/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading”/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List”/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid”/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List”/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading”/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List”/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid”/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 1″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 1″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 1″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 1″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 1″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 1″/>
<w:LsdException Locked=”false” UnhideWhenUsed=”false” Name=”Revision”/>
<w:LsdException Locked=”false” Priority=”34″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”List Paragraph”/>
<w:LsdException Locked=”false” Priority=”29″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Quote”/>
<w:LsdException Locked=”false” Priority=”30″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Intense Quote”/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 1″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 1″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 1″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 1″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 1″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 1″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 1″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 1″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 2″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 2″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 2″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 2″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 2″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 2″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 2″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 2″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 2″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 2″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 2″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 2″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 2″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 2″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 3″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 3″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 3″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 3″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 3″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 3″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 3″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 3″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 3″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 3″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 3″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 3″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 3″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 3″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 4″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 4″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 4″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 4″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 4″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 4″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 4″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 4″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 4″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 4″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 4″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 4″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 4″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 4″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 5″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 5″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 5″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 5″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 5″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 5″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 5″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 5″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 5″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 5″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 5″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 5″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 5″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 5″/>
<w:LsdException Locked=”false” Priority=”60″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Shading Accent 6″/>
<w:LsdException Locked=”false” Priority=”61″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light List Accent 6″/>
<w:LsdException Locked=”false” Priority=”62″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Light Grid Accent 6″/>
<w:LsdException Locked=”false” Priority=”63″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 1 Accent 6″/>
<w:LsdException Locked=”false” Priority=”64″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Shading 2 Accent 6″/>
<w:LsdException Locked=”false” Priority=”65″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 1 Accent 6″/>
<w:LsdException Locked=”false” Priority=”66″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium List 2 Accent 6″/>
<w:LsdException Locked=”false” Priority=”67″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 1 Accent 6″/>
<w:LsdException Locked=”false” Priority=”68″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 2 Accent 6″/>
<w:LsdException Locked=”false” Priority=”69″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Medium Grid 3 Accent 6″/>
<w:LsdException Locked=”false” Priority=”70″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Dark List Accent 6″/>
<w:LsdException Locked=”false” Priority=”71″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Shading Accent 6″/>
<w:LsdException Locked=”false” Priority=”72″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful List Accent 6″/>
<w:LsdException Locked=”false” Priority=”73″ SemiHidden=”false”
UnhideWhenUsed=”false” Name=”Colorful Grid Accent 6″/>
<w:LsdException Locked=”false” Priority=”19″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Subtle Emphasis”/>
<w:LsdException Locked=”false” Priority=”21″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Intense Emphasis”/>
<w:LsdException Locked=”false” Priority=”31″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Subtle Reference”/>
<w:LsdException Locked=”false” Priority=”32″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Intense Reference”/>
<w:LsdException Locked=”false” Priority=”33″ SemiHidden=”false”
UnhideWhenUsed=”false” QFormat=”true” Name=”Book Title”/>
<w:LsdException Locked=”false” Priority=”37″ Name=”Bibliography”/>
<w:LsdException Locked=”false” Priority=”39″ QFormat=”true” Name=”TOC Heading”/>
</w:LatentStyles>
<![endif]–><!– [if gte mso 10]>

<style> /* Style Definitions */ table.MsoNormalTable {mso-style-name:”Tabela normal”; mso-tstyle-rowband-size:0; mso-tstyle-colband-size:0; mso-style-noshow:yes; mso-style-priority:99; mso-style-parent:””; mso-padding-alt:0cm 5.4pt 0cm 5.4pt; mso-para-margin-top:0cm; mso-para-margin-right:0cm; mso-para-margin-bottom:10.0pt; mso-para-margin-left:0cm; line-height:115%; mso-pagination:widow-orphan; font-size:11.0pt; font-family:”Calibri”,”sans-serif”; mso-ascii-font-family:Calibri; mso-ascii-theme-font:minor-latin; mso-hansi-font-family:Calibri; mso-hansi-theme-font:minor-latin; mso-fareast-language:EN-US;} </style>
<![endif]–>

**Comment by gusfune** [comment]
Coloquei o editor de TEXTO como default por hora.
O problema pode continuar a rolar no editor visual pois aparentemente o usuário escreveu o texto no Word e colou no editor visual. Existe de fato um bug cadastrado nos fóruns de WP ligado a isso.
Seria possível pedir pro usuário enviar o .DOC do post dele pra eu fazer uns testes? Vi algumas soluções, porém, o meu Word é o mais recente e de Mac então não deu pra replicar. Se conseguir esse DOC da pra resolver o problema com alguns ajustes.

**Comment by eduardoamuri** [comment]
Gus, por enquanto, ficaremos dessa forma. 

Faremos uma reunião na semana que vem, contigo, conversamos sobre essa issue.

Estou tirando a prioridade.

**Comment by gusfune** [comment]
@eduardoamuri eu vou estar fora até dia 05/02, se precisarmos reunir vai ter que ser depois dessa data.
O problema como indiquei, ta relacionado a colar do Word no campo. Vamos conversar sobre isso com mais detalhes e seguimos ok?
