### ISSUE TITLE
Mobile: inserir campo de busca

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#28]
Gus, tem gente acessando mobile direto, então seria muito importante colocar o campo de busca. Você consegue em cima, como é no site, na mesma linha do avatar logado?

Daí na listagem de resultados você pode fazer como é na listagem de práticas, uma debaixo da outra. O foda é que ele busca só o que está nas práticas / posts, não no fórum.

Para mostrar a busca no fórum, teria de inserir o campo de busca na visualização das páginas de fóruns e listas de tópicos (não precisa na visualização de mensagens, dentro de cada tópico). Acha que rola?

@gusfune 

@eduardoamuri vai acompanhar enquanto eu estiver fora na semana que vem

Valeu!

**Comment by gusfune** [comment]
A listagem é tranquilo pois a página já ta preparada pra responsivo.

A busca em si no topo a gente precisaria dar uma adaptada, o ideal seria ter o ícone de busca ao lado do inscrever-se/entrar e ao clicar o campo fica por cima da barra toda, pois em dispositivos menores pode não caber.

Podemos fazer dessa forma? Ou tem outra sugestão?

**Comment by eduardoamuri** [comment]
Gus, 

Vamos fechar esse tópico e abrir outro, com outro pedido que faz mais sentido.
