### ISSUE TITLE
Fixar dois posts na home fechada

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#29]
Gus, fizemos uma mudança importante na operação do lugar: agora, em vez do percurso individual, todo mundo será convidado a cada semana para focar em apenas uma prática. Todo mundo com um só foco. Descobrimos que isso funciona bem melhor!

Então, precisamos que você use deixe alguma opção para fixarmos sempre duas práticas na home: a da semana atual e a da passada. Hoje está por data, então ficamos sempre mudando a data... Pode ser um lugar no admin pra escolher prática atual e prática passada. Ou pode ser um checkbox tipo "sticky" dentro do editor de cada prática (tenho um tema que fez assim).

Depois vou pensar com calma em um layout só pra deixar o post da semana atual, mas daí essa solução do sticky já estará pronta e pode ser usada igualzinho.

@eduardoamuri @gusfune 

Valeu!

**Comment by gusfune** [comment]
Vocês acham melhor criar uma opção de marcar "prática em destaque" e ele exibir duas que estiverem marcadas, ou marcar uma data de quando essas práticas entram e ele pegar sempre as duas últimas duas semanas?

**Comment by eduardoamuri** [comment]
Preferimos a ideia da "Prática em destaque". 

Pode ser a opção que ficar mais simples:

1) Dentro de cada prática, temos um check-box com "Prática em destaque" ou;

2) Em outro lugar, temos um menu drop-down com todas as práticas e selecionamos de lá. 

Obrigado.

**Comment by gusfune** [comment]
Feito no Beta. Pode verificar/validar? Se estiver ok dessa forma, subimos o dropdown em produção, vcs marcam as duas da semana e subimos.
Se preferir selecionar também qual vai em cada posição, podemos ajustar.

**Comment by eduardoamuri** [comment]
Ficou ótimo, já testei por aqui.

**Comment by gusfune** [comment]
Subi já o seletor em produção, mas não o ajuste visual.
Podem subir 2 posts e me confirmar que ta no ar pra subir o fix e aparecer certinho lá?

**Comment by eduardoamuri** [comment]
Pode subir o fix, já marquei dois posts com "SIM".

**Comment by gusfune** [comment]
Feito e publicado!

**Comment by eduardoamuri** [comment]
perfeito.

**Comment by eduardoamuri** [comment]
Gus, da forma que está, continuamos tendo que mexer na data... precisamos que, no menu drop, tenha "primeiro destaque", "segundo destaque" ou "sem destaque". Pode ser?

**Comment by gusfune** [comment]
Eu perguntei isso antes...
Bem, vou alterar e subir quando terminar o servidor, senão ele vai ficar pendurado na metade e não fica pronto. Retorno em breve.

**Comment by eduardoamuri** [comment]
Vacilo meu, desculpe.

**Comment by gusfune** [comment]
Da uma olhada no beta @eduardoamuri pra ver se a forma que subi ta 100%? Estando ok, eu subo os seletores novos em produção e ajusto os posts lá.

**Comment by gusfune** [comment]
Publicado fix em produção. Mantive os posts que estavam em destaque lá.
