### ISSUE TITLE
Usuários não conseguem alterar fotos de imagem de capa ou avatar no perfil

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#3]
As pessoas não conseguem alterar a foto nem a imagem de capa na página de perfil.

**Comment by gustavogitti** [comment]
Gus, consegue resolver isso logo e já subir? Tá uma dor de cabeça... Eu fui trocar minha foto e agora tem só um borrão verde... Na hora do crop ele não mostra a ferramenta de crop e daí ele salva uma imagem bizarra em vez da foto...

**Comment by gusfune** [comment]
Essa issue eu to quebrando a cabeça tem um tempo. Eu descobri o problema/causa que é a série de plugins do BBPress JQuery estarem carregando no lugar errado, mas não achei como resolver. Meio caminho andado, talvez leve mais um tempo, mas já ta entendido.

**Comment by gustavogitti** [comment]
Beleza. Estranho porque antes funcionava numa boa.

**Comment by gusfune** [comment]
Parou de funcionar depois do refactor do site? Ou tava funcionando depois dele e quebrou depois? Ou antes do refactor já viu o problema? Isso ajuda bastante pra entender o problema específico, até pq envolve um item que eu desconfio.

**Comment by gusfune** [comment]
Achei o problema, era um ajuste de uma linha de código no tema pra chamar os scripts. Corrigido e subi direto pra produção já por não afetar nada do funcionamento do site.
