### ISSUE TITLE
Configurar DNS para autenticação melhorada dos emails do Mailchimp

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#31]
Gus, o que acha de fazermos isso?

http://kb.mailchimp.com/accounts/email-authentication/about-email-authentication?

Seguem as infos que peguei, é só implementar no servidor e me avisar pra eu dar OK no admin do Mailchimp:

Authenticate olugar.org with MailChimp by modifying your domain's DNS records. These changes allow your campaigns to appear to come from olugar.org, instead of from our servers. After you've made the required DNS changes, please wait 24-48 hours for the changes to propagate. Why should I do this?

DKIM: Create a CNAME record for k1._domainkey.olugar.org with this value:
dkim.mcsv.net

SPF: Create a TXT record for olugar.org with:
v=spf1 include:servers.mcsv.net ?all

...

Vamos ter de testar bastante depois porque isso é crucial, então se der merda, voltamos, tá bem? Mas parece que vai melhorar o open rate, não vai chegar tanto no spam com o tempo.

@eduardoamuri @gusfune

**Comment by gusfune** [comment]
Isso foi feito já em Outubro/2016, conforme issue #19. Estou fechando o pedido pois já está funcionando dessa forma.

Se o problema de spam persiste, deve ser avaliado com cuidado em outras frentes.
