### ISSUE TITLE
Mobile: home

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#32]
Gus, na home fechada (logada) do mobile, por favor mostra primeiro as práticas da semana e o fluxo resumido, e só depois os elementos da sidebar. Agora tá mostrando o que está na sidebar e só depois as duas práticas e as mensagens do fluxo. Beleza?

**Comment by gusfune** [comment]
Por conta da estrutura do site hoje, a melhor forma de corrigir é na verdade alterarmos pra que esconda em dispositivos muito pequenos, ta feito já.
