### ISSUE TITLE
Modificações na inserção de imagem

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#36]
Gus, por favor, duas pequenas modificações: 

1) Alterar o texto "Adicionar mídia" para "Adicionar imagem";
![screen shot 2017-01-20 at 10 19 46 am](https://cloud.githubusercontent.com/assets/247457/22149336/4b37c622-defa-11e6-84b0-07d4a2936bb6.png)

2) Setar o "Tamanho completo" como default, na hora de adicionar uma imagem.
![screen shot 2017-01-20 at 10 19 27 am](https://cloud.githubusercontent.com/assets/247457/22149345/585f99b0-defa-11e6-8e19-62753735d29c.png)

**Comment by gusfune** [comment]
Ambas configurações são padrões do Wordpress da seguinte forma:
- O texto do botão tem como trocar mexendo na tradução do Wordpress, mas isso vai se perder a cada update. Eu recomendo aprenderem a se acostumar com "Adicionar mídia" mesmo do que tentar customizar um detalhe que pode confundir depois ou ficar dando manutenção pra detalhe.
- O tamanho completo como default é a última opção usada. Nem sempre funciona, mas esse autoselect não da pra fazer sem mudar o core do Wordpress, e fazendo isso também vai se perder a cada update.
