### ISSUE TITLE
Refazer o header do mobile

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#38]
Gus, pensamos em algo assim: 

![screen shot 2017-02-22 at 4 22 30 pm](https://cloud.githubusercontent.com/assets/247457/23229294/8ad512c4-f91e-11e6-99d7-66ec9ca882ec.png)

Gostaríamos também de simplificar o menu. Não gostaríamos que os subitens aparecessem. É possível? O subitem "Mais" também não vai aparecer.

Na prática ficaríamos com:

-- Comece aqui
-- Práticas
-- Fórum
-- Ao vivo
-- Fluxo

Nos avise para seguirmos.

**Comment by gusfune** [comment]
Fiz o seguinte (podem ver no beta):
- Criei um menu separado pros elementos do Mobile pro Desktop, ta certo? Ou preferem manter um menu só pros dois, sendo que no mobile fica sem sub-níveis? Preciso saber isso certinho.

Falta ainda coisa, ainda mais relacionado a avatar/logo do lugar, porém, to indo com uma coisa de cada vez.

**Comment by gusfune** [comment]
Ta pronto o header mobile, podem validar já no beta.

**Comment by eduardoamuri** [comment]
Esta lindo o design, mas não aparecem os itens. Além disso, por favor, da uma conferida dos updates. A versão de prd tá diferente do beta. O texto não aparece em beta (da pag aberta).

**Comment by eduardoamuri** [comment]
O menu que aparece no scrolling up precisa ser atualizado também.

**Comment by gusfune** [comment]
> A versão de prd tá diferente do beta. O texto não aparece em beta (da pag aberta).
Não entendi o problema, a priori o que ta diferente são as imagens com problema.

> O menu que aparece no scrolling up precisa ser atualizado também.
Você quer que ele fique igual ao menu quando no topo ou diferente? Me confirma pra ajustar?

**Comment by eduardoamuri** [comment]
> Não entendi o problema, a priori o que ta diferente são as imagens com problema.

Veja os prints abaixo, Gus: 

BETA: 
![whatsapp image 2017-02-27 at 7 48 14 am 1](https://cloud.githubusercontent.com/assets/247457/23358749/f4ab5734-fcc1-11e6-8c0a-2fa2ead917cc.jpeg)

PRD:
![whatsapp image 2017-02-27 at 7 48 14 am](https://cloud.githubusercontent.com/assets/247457/23358755/fa467f48-fcc1-11e6-9383-8bd3f7bb4ac6.jpeg)

No BETA faltam vários elementos (logotipo, texto de apresentação...) 

* * * 

> Você quer que ele fique igual ao menu quando no topo ou diferente? Me confirma pra ajustar?

Sim, pode ficar igual. Sempre o header slim, com hamburguer na esquerda, logotipo e foto (no mobile, claro).

* * * 

> Criei um menu separado pros elementos do Mobile pro Desktop, ta certo? Ou preferem manter um menu só pros dois, sendo que no mobile fica sem sub-níveis? Preciso saber isso certinho.

Agora entendi. 

Sem problemas termos dois menus diferentes, acho ótimo.

**Comment by gusfune** [comment]
Corrigi parte do item (de elementos faltando), mas na rolagem o menu não ta 100% ainda.
Vou esperar o carnaval passar pra passar pro dev que montou o CSS todo do site pq eu to arrumando de um lado e quebrando outro, dai ao invés de ficar gastando horas atoa (e ficando mais caro), eu foco nos outros itens pendentes.

**Comment by eduardoamuri** [comment]
Por enquanto, pode tirar o menu do scrolling up do mobile, então. 

O menu mobile ainda está vazio por aqui.

**Comment by gusfune** [comment]
Ok! O vazio foi falha minha, consertado já. Retomamos isso em breve.

**Comment by eduardoamuri** [comment]
Chegou a tirar o scrolling up? 

O restante está ok.

**Comment by eduardoamuri** [comment]
Subiremos para PRD com o menu estável, pós-carnaval.

**Comment by gusfune** [comment]
@eduardoamuri, finalizamos aqui essa parte, pode conferir no beta.olugar.org? Basta da ok na issue #48 que solicitei o review que tendo ok subimos em PRD.

**Comment by eduardoamuri** [comment]
Gus, rola dar uma testada ai antes de eu fazer o pente fino? Abri a tela e tá toda desfigurada. :(

**Comment by gusfune** [comment]
Limpa o cache antes de testar. Testei aqui antes de liberar.
-- 

--
*Gus Fune*
Executive Producer
Mobile: +55 (61) 982-109-400
Office Brasília: +55 (61) 4042-5005 ext. 8088
Office São Paulo: +55 (11) 4200-2013 ext. 8088
Office US Toll-Free: +1 (844) 600-EPIC  ext. 8088

**Comment by eduardoamuri** [comment]
Gus, na página não logada o menu se perde, encavala e o botão não funciona.

**Comment by eduardoamuri** [comment]
![whatsapp image 2017-03-07 at 9 02 25 pm](https://cloud.githubusercontent.com/assets/247457/23683966/b139df24-037a-11e7-8502-f7f9adff04d2.jpeg)

**Comment by gusfune** [comment]
@eduardoamuri subimos um update aqui no https://beta.olugar.org/aberto/, pode verificar?
Não testa sem o `/aberto/` pq isso ta ligado ao WooCommerce e nao ta concluído.

**Comment by eduardoamuri** [comment]
Gus, o menu logado tá perfeito, o não logado segue com o mesmo erro, ja atualizei o cache. Não sei se eu me expressei mal, mas o menu não logado já estava perfeito em produção, não precisa alterar nada!

**Comment by gusfune** [comment]
Perfeito.
Ta em produção já 100%, qualquer problema me avisa.
