### ISSUE TITLE
Botão "Adicionar mídia" não aparece

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#39]
Gus,

O botão "Adicionar mídia" (para inserir uma imagem no post do fórum) só aparece para administradores. 

Para testar: 

usuário: junqueira
senha: junqs#123

**Comment by gusfune** [comment]
Isso é padrão de segurança do BBPress. Permitir o upload de imagem de usuários abre precedente para subirem potenciais malware. Quer mesmo liberar?

**Comment by eduardoamuri** [comment]
Sim, acho que vale o risco. 

Pode subir.

**Comment by eduardoamuri** [comment]
Esse item vai subir pra prod também, certo?

**Comment by gusfune** [comment]
Agora ainda não, to tentando descobrir pq não libera o acesso mesmo com o código no ar. Vamos retomar depois de implementar o WooCommerce.

**Comment by eduardoamuri** [comment]
Vamos retomar essa aqui, Gus? :)

**Comment by gusfune** [comment]
Desabilitei os email tudo no beta. Pode validar antes de subir?

**Comment by gusfune** [comment]
Vamo nãaao, fiquei aqui quase meia hora, consegui de uma forma, mas não ta muito bom.
Vou precisar de mais tempo pra tentar com mais detalhes.

**Comment by eduardoamuri** [comment]
Falamos sobre ele hoje, 11/04.

**Comment by gusfune** [comment]
Não consegui fazer o botão "adicionar mídia" funcionar sem zoar todas as permissões do Wordpress (e basicamente liberar o upload de qualquer tipo de arquivo pra qualquer usuário logado).

Porém, dando uma pesquisada achei um plugin que permite anexos no BBPress, ele adiciona um campo de anexo ao final. Não é a solução "smooth" como o botão adicionar mídia, mas funciona e não gera os riscos de segurança que seria apenas alteras as permissões gerais.

Podem verificar no Beta? Estando ok, eu libero o plugin em produção.
Eu habilitei um plugin no beta chamado "user switch" que permite "logar" instantaneamente como qualquer usuário a partir da lista de usuários (basta ser admin).

**Comment by eduardoamuri** [comment]
Gus, o beta está inteiro fora do ar, veja:

![screen shot 2017-04-13 at 8 09 50 am](https://cloud.githubusercontent.com/assets/247457/25002403/a3269054-2020-11e7-87c6-be64615c029f.png)
![screen shot 2017-04-13 at 8 09 08 am](https://cloud.githubusercontent.com/assets/247457/25002402/a3231f46-2020-11e7-9070-d52c74b11de7.png)

**Comment by gusfune** [comment]
Tenta de novo? Resolvido.
