### ISSUE TITLE
Remover algumas atualizações do fluxo de atividade

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#4]
Se der, remover do fluxo a atividade "mudou sua foto" (https://olugar.org/pessoas/carol/activity/19284/) e "profile was updated" (https://olugar.org/pessoas/carol/activity/19285/). As outras estão OK.

**Comment by gusfune** [comment]
Corrigido, ta no beta.
Fiz um filtro pra esconder esses dois tipos de atualizações via CSS.

**Comment by gustavogitti** [comment]
Beleza, pode subir!
