### ISSUE TITLE
Alteração no avatar do forum

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#41]
Hoje aparece o nome da pessoa, o nome de usuário e o IP.

Queremos trocar a informação do IP pelo last login.

![screen shot 2017-02-23 at 9 45 48 am](https://cloud.githubusercontent.com/assets/247457/23259664/ef3a7ffe-f9ac-11e6-938e-2eedec60b30c.png)

**Comment by gusfune** [comment]
Isso seria pra todos ou só pro admin?
O IP é um dado restrito só pro admin, o last login seria também?
Em algum outro lugar é exibido esse dado?

**Comment by eduardoamuri** [comment]
Pode mostrar pra todos. Será exibido só ali.

**Comment by gusfune** [comment]
Batendo cabeça aqui em como alterar isso sem ter que mexer em core-files do bbpress. Deixando on-hold pra não atrasar outras coisas.

**Comment by eduardoamuri** [comment]
Tranquilo. :)

**Comment by eduardoamuri** [comment]
Falamos sobre hoje 11/04.

**Comment by gusfune** [comment]
Consegui fazer, depois de bastante bater a cabeça.
Basicamente tive que fazer uma engenharia reversa no BBPress pra descobrir como ele puxa os dados do autor, pra ver como o Buddypress faz isso, e jogar no lugar certo. Agora ta pronto, no máximo vamos precisar estilizar uns detalhes.

Podem validar no beta já.
Ref: https://beta.olugar.org/forums/topic/para-ficarmos-mais-proximos/
<img width="959" alt="screenshot 2017-04-11 23 58 10" src="https://cloud.githubusercontent.com/assets/1147240/24939302/c28422e0-1f12-11e7-874a-dec1e3259a5c.png">

**Comment by eduardoamuri** [comment]
Tá joia, pode subir.

**Comment by gusfune** [comment]
Tenta de novo? Resolvido.
