### ISSUE TITLE
Validar novo servidor

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#44]
Novo servidor ta pronto e configurado. O BETA foi copiado pra lá: beta.olugar.org.
Podem dar uma geral e ver se ta 100%? Estando ok, migramos o site e seguimos em frente com os ajustes.

**Comment by eduardoamuri** [comment]
A princípio esta tudo certo, exceto o menu, que está o antigo. Testarei com mais calma logo mais!

**Comment by gusfune** [comment]
Ok. Me avisa terminando os testes @eduardoamuri que a gente consegue migrar depois o lugar pro novo servidor. O menu eu ainda não reinstalei no beta, isso vai ser feito ainda hoje mais tarde.

**Comment by eduardoamuri** [comment]
Tudo ok com o novo servidor (salvo o menu, que está funcionando direitinho, embora vazio, porém não está implementado no scrolling up).

**Comment by gusfune** [comment]
O menu eu esqueci de linkar, falha minha. De qualquer forma, retomamos isso logo depois do carnaval. Voltando atrás no menu.

**Comment by gusfune** [comment]
Com isso acho que ta 100% o servidor. Eu vou fechar alguns ajustes no servidor e migramos na madrugada, ok?

**Comment by eduardoamuri** [comment]
OK.

**Comment by gusfune** [comment]
Migrado com sucesso!

**Comment by eduardoamuri** [comment]
As telas estão completamente vazias, Gus.

**Comment by eduardoamuri** [comment]
Gus,

Seguindo.

a) O servidor parece estar ok, o problema é a renderização das duas homes. Quando abrimos alguma página, em específico, tudo funciona. (o /praticas, por exemplo). O processo de login também funciona, apesar de não renderizar a home logada. 

b) O botão de logout sumiu. 

c) O link "quem somos", do rodapé, está levando para o ambiente de PRD. 

d) O /carrinho parece estar funcionando, apesar de não conseguirmos resolver os testes por completo. A lista de estados não está sendo carregada corretamente (ele sempre puxa estados do EUA): 

![screen shot 2017-03-01 at 9 33 17 am](https://cloud.githubusercontent.com/assets/247457/23460106/3c3d5222-fe62-11e6-81ac-205993d7dc1a.png)

Consegui chegar quase até o final, quando ele me joga para o Paypal. Isso não vai mais existir quando implementarmos o checkout transparente, certo?

![screen shot 2017-03-01 at 9 36 10 am](https://cloud.githubusercontent.com/assets/247457/23460160/961df364-fe62-11e6-831c-1ff9b7ccd3d7.png)

Seguimos. :)

**Comment by gusfune** [comment]
Agora me confundiu tudo aqui. O que é bug do servidor/PRD e o que ta no beta/WooCommerce? O que for de woocommerce, pode colocar direto na issue #45 pra gente não misturar as coisas?

**Comment by eduardoamuri** [comment]
Atualizei meus comentários tanto aqui quando na issue #45.

**Comment by gusfune** [comment]
Esses 3 itens são no beta ou PRD? Pq a priori está tudo ok em PRD.

**Comment by eduardoamuri** [comment]
Tudo no beta, Gus. 

Em prod está tudo ok. 

Resumindo: 

Em PRD: tudo ok. 

Em BETA: 

a) As homes não renderizam

b) O botão de logout sumiu.

c) O link "quem somos", do rodapé, está levando para o ambiente de PRD.

**Comment by eduardoamuri** [comment]
Gus, 

Conseguiu atacar esses pontos?

Me avisa?

**Comment by gusfune** [comment]
Os itens ligados a menu/woocommerce estão sendo feitos. com servidor no ar vou fechar a issue pois já temos servidor no ar.
