### ISSUE TITLE
Adicionar "Novos usuários" no nosso painel de usuário

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#46]
No admin do wordpress, temos um php que gera algumas listas uteis para nossa gestão. É a admin.php?page=gasoline-dashboard. 

Queremos uma nova listinha nessa mesma página, logo em cima, com as informações dos usuários que  acabaram de cadastrar no WP.

Seria ótimo termos os campos que as outras listas já tem, mais o número do celular. 

Obrigado.

**Comment by gusfune** [comment]
Pelo que eu entendi, esse plugin foi feito customizado especialmente para o Lugar, certo?
Só pra entender melhor pois a gente vai precisar dar uma mexida nesse plugin pra usar a mesma base pra criar as novas seções. Me passem as infos que precisam certinho?

**Comment by eduardoamuri** [comment]
Foi sim.

É muito simples, um PHP só, eu mesmo atualizei da última vez. 

Vamos precisar dessa listagem básica, com quem criou um usuário no WP nos últimos 7 dias.

Nome, e-mail, nome de usuário (com link para o perfil) e celular, já basta. :)

**Comment by gustavogitti** [comment]
Lembra de colocar celular em todas as listas (na atual e na nova, de Novos usuários).

**Comment by eduardoamuri** [comment]
Falamos sobre isso hoje, 11/04.

**Comment by gusfune** [comment]
Consegui fechar aqui e dei uma melhorada no plugin. Preciso que verifiquem pra ver se é isso mesmo que querem: https://beta.olugar.org/wp-admin/users.php?page=gasoline-dashboard-options

Eu inclusive, fiz um ajuste pra tirar um item de menu (tava achando over) e jogei esse dashboard pra dentro de `Usuários->Acolhimento`. Assim que validarem a gente manda pra produção.

**Comment by eduardoamuri** [comment]
gus, faltou o celular! :)

**Comment by gusfune** [comment]
Exibir o celular do usuário na listagem? Em todas as listas ou apenas a de novos membros?

**Comment by gusfune** [comment]
Subir o celular e fechou.
