### ISSUE TITLE
Alterações no menu mobile

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#49]
Hoje o menu mobile contempla os itens: 

-- COMECEI AQUI
-- PRÁTICAS
-- FÓRUM
-- AO VIVO
-- FLUXO
-- MAIS

Precisamos tirar o item "MAIS" e incluir um "SAIR", com a função de logout.

**Comment by gusfune** [comment]
Feito. Só atenção:
- O MAIS eu corrigi direto nos menus do Wordpress, então ta em produção o correto e não no beta.
- O SAIR ta o preview no BETA pois envolve ajuste de código.

Dando ok a gente fecha e sobe.

**Comment by eduardoamuri** [comment]
Pode subir.

**Comment by gusfune** [comment]
Feito.

**Comment by eduardoamuri** [comment]
Gus, o botão sair está levando para a tela: "Quer entrar ou voltar para ao lugar?", deveria levar para o /aberto.

**Comment by gusfune** [comment]
Agora não ta mais!
