### ISSUE TITLE
Traduzir itens faltantes

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#5]
Precisamos traduzir o que restou, tipo "one minute ago", "members" etc.

**Comment by gusfune** [comment]
@gustavogitti e @eduardoamuri conseguem identificar se os itens específicos de tradução são do BBPress, Buddypress, S2Member ou ambos? Ajudaria a ver aqui qq pode ser esse detalhe.

**Comment by eduardoamuri** [comment]
Gus, não consigo fazer essa distinção, por não conhecer detalhes da arquitetura. É bem fácil de notar, porém... é só navegar por 2 ou 3 páginas que você vai ver um monte de coisas.

**Comment by gusfune** [comment]
@eduardoamuri eu dei uma fuçada aqui em várias páginas: posts, edição de perfil, comentários, respostas de tópicos, fluxo, etc e não encontrei nenhum termo em inglês. @gustavogitti pode dar um help já que solicitou o ajuste? Acredito que isso possa ter sido resolvido com update que fiz no Wordpress, mas preciso confirmar antes de fechar a demanda.

**Comment by eduardoamuri** [comment]
Tudo certinho, Gus.

Deve ter resolvido com o update. :)
