### ISSUE TITLE
Post feito no fórum gera várias ocorrências no Fluxo ("Mais recentes") 

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#51]
![screen shot 2017-03-08 at 6 29 42 pm](https://cloud.githubusercontent.com/assets/247457/23724911/59747e94-042d-11e7-8a5b-1a7518d084f4.png)

**Comment by gusfune** [comment]
Isso é o mesmo problema que ocorria antes ou é novo?
É aquele de editar e ele posta novamente?

**Comment by eduardoamuri** [comment]
Gus, segundo os caseiros (que acompanham o fórum todos os dias), o mesmo problema voltou.

De todo jeito, por favor, vamos priorizar o Woo. :)

**Comment by gusfune** [comment]
Ok, ta na fila aqui.

**Comment by gusfune** [comment]
Eu cheguei a subir um fix disso quando subi o WooCommerce, vê se ainda ta rolando? Fiz depois de atualizar o BBpress/Buddypress.

**Comment by eduardoamuri** [comment]
Não está mais ocorrendo! :) 

Issue fechada.
