### ISSUE TITLE
Fazer limpeza de páginas cadastradas

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#53]
Pra facilitar o processo de travar conteúdos, preciso que páginas antigas, rascunhos e que não serão utilizadas sejam limpas do Wordpress. Hoje tem mais de 3 páginas de conteúdo e isso vai dar um trabalho manual grande na hora de setar as permissões de conteúdo.

https://beta.olugar.org/wp-admin/edit.php?post_type=page

**Comment by eduardoamuri** [comment]
@gustavogitti , me ajuda com essa?

**Comment by gustavogitti** [comment]
Feito!
