### ISSUE TITLE
Migração de usuários S2Member->WooCommerce

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#54]
@eduardoamuri criei uma issue separada pra gente discutir a migração do S2Member pro WooCommerce, pois os usuários que pagam pelo PayPal precisam ser migrados.

Temos algumas formas de resolver essa questão depois de configurar o WooCommerce:
1. Subir manualmente uma assinatura default sem vencimento pros usuários e dai você vai gerindo manualmente a assinatura de cada um.
2. Subir manualmente uma assinatura de cada um colocando a data de vencimento de cada um, dai renovar na mão cada um.

O ideal seria migrar esses usuários gradualmente do PayPal pro Stripe, porém isso só da pra fazer uma vez eles entrando na tela de compras e assinando pela tela do Stripe. Isso pode gerar perda de assinaturas.

Os plugins que temos permitem criarmos um produto exclusivo pra quem já tem assinatura (depois de migrar manualmente as assinaturas), assim eles podem assinar. Uma forma de motivar a migrarem o sistema seria criar essa assinatura com o preço de hoje e pra novos assinantes subir o valor da mensalidade.

De qualquer forma, existe uma dor de cabeça e trabalho manual com esses usuários. Isso vocês podem fazer, ou posso alocar alguém aqui pra fazer em paralelo quando for subir os sistemas, o que for mais eficiente. O mais importante é fazemos tudo junto pra evitar muito downtime do lugar.

Como acham melhor seguir?

**Comment by gusfune** [comment]
Novidades aqui por aqui @eduardoamuri e @gustavogitti, encontrei uma forma segura de migrarmos as assinaturas pro novo sistema com muito menos trabalho manual.

Basicamente a gente pode importar um CSV direto que vai associar todos os assinantes do paypal ao membership equivalente no WooCommerce. Só vamos precisar inicialmente de uma planilha que tenha o Email desses usuários ativos, e caso tenha a data de vencimento das assinaturas, isso já pode ser inserido/automatizado pro WooCommerce.

Ou seja, eliminamos o trabalho manual de associar um por um as assinaturas. O que reduz bastante o tempo de migração.

O que fica pendente é qual o plano pra subir a data de vencimento de cada assinatura, ou se isso vai ser gerido na mão até ser feito toda migração pro sistema com Stripe.

No aguardo pra gente fechar isso pra poder seguir.

**Comment by eduardoamuri** [comment]
Faremos tudo na mão, Gus, para reduzir o risco. Migra tudo pro woo, e deixa as datas sendo geridas pelo paypal, como é hoje. :)

**Comment by gusfune** [comment]
@eduardoamuri 100% de certeza? Dessa forma pelo menos a gente evita um gap de usuários sem acesso, depois da pra alterar manualmente as assinaturas. Podemos rodar um teste no BETA pra garantir.

**Comment by eduardoamuri** [comment]
A migração pode acontecer via script ou csv, mas não mexeremos em nada no paypal. Gerenciaremos tudo na mão, foi o que eu quis dizer :)

**Comment by gusfune** [comment]
Exato. A ideia é migrar todos pra uma assinatura ilimitada (sem vencimendo) no woocommerce e dai gerenciarem na mão. Isso funciona pra vcs 100%?

**Comment by eduardoamuri** [comment]
Sim, mas ainda quero um skype contigo antes. :)

**Comment by gusfune** [comment]
Claro. Quer já marcar certinho a data?
