### ISSUE TITLE
Tradução de elementos em inglês no WooCommerce

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#59]
Os itens em inglês são do WooCommerce Subscriptions e do Membership, que a tradução oficial não existe, e a feita pela comunidade foi parcialmente feita.

Essa parte eu vou precisar de um help de vocês. Minha sugestão é traduzir direto no projeto público de tradução, pois ai fica disponível pra outras pessoas e não "quebra" em qualquer update do plugin.

https://translate.wordpress.com/projects/woocommerce/woocommerce-subscriptions/pt-br/default/
https://translate.wordpress.com/projects/woocommerce/woocommerce-memberships/pt-br/default/

Eu não sei qual dos dois plugins ta puxando os termos em inglês, então sugiro pra ganhar tempo traduzir os termos que identificarem em português.

Vale lembrar que além do checkout existe a seção de gerenciar a assinatura: https://beta.olugar.org/minha-conta/

**Comment by eduardoamuri** [comment]
Não temos nenhum termo em ingles no site atualmente.
