### ISSUE TITLE
Implementar Cache no site

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#61]
Implementar melhoria de performance no site.

**Comment by gusfune** [comment]
@eduardoamuri e @gustavogitti, terminei de implementar o cache no beta para testar uma possível otimização do carregamento das páginas do Lugar. Podem avaliar pra ver se ta 100% pra gente poder subir em produção?

## Comparativo
### Antes
<img width="1228" alt="screenshot 2017-03-24 17 07 22" src="https://cloud.githubusercontent.com/assets/1147240/24311965/3970f822-10b5-11e7-8431-4eb5f728db55.png">

### Depois
<img width="1229" alt="screenshot 2017-03-24 17 13 47" src="https://cloud.githubusercontent.com/assets/1147240/24311977/46af6c80-10b5-11e7-892a-a31408bfa13f.png">

A ideia é melhorar esse score, mas 5% já é um começo. Vamos deixar essas notas com A no decorrer do tempo.

**Comment by eduardoamuri** [comment]
Está ok, Gus. 

Por favor, coloque um cache com expiração rápida, ok? Para que todo mundo consiga ver rapidamente as novas postagens de fórum. :)

**Comment by gusfune** [comment]
Fechado!
