### ISSUE TITLE
Desinstalar S2Member em Produção

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#62]
- [x] Migrar membros Level 1 pra novo Role de "Cursos"
- [x] Fazer o processo completo de desinstalação: https://s2member.com/kb-article/how-do-i-uninstall-s2member/

**Comment by gusfune** [comment]
Fiz o processo no BETA, pode dar um check @eduardoamuri?
No caso a gente precisa migrar os usuários level 1 pra acesso de cursos. Me descreve aqui que acessos esses usuários precisam pra preparar a migração disso?

**Comment by eduardoamuri** [comment]
Vou validar em produção, mas prefiro fazer a migração quando o Fábio voltar de férias, daqui 3 semanas, tudo bem?

**Comment by gusfune** [comment]
Ok. Só me avisa pq isso vai dar uma boa aliviada no banco de dados.
