### ISSUE TITLE
Criação de tela "Assinatura feita com sucesso"

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#63]
Gus, 

Utilizaremos uma tela básica, padrão, com o usuário já logado. 

O texto inicial será esse aqui: 

Título: Tudo certo com sua assinatura :)
Texto: Você já deve ter recebido um e-mail de confirmação, com alguns dados importantes relativos a sua conta. 

Se você tiver qualquer dúvida, fique à vontade para entrar em contato através do coordenacao@olugar.org. 

Clicando *neste link*, você será redirecionado para nossa tela de boas vindas. 

Desejamos, de coração, que você se beneficie do espaço. 

Seguimos.

Você pode criar a page, a gente refina depois? Pode colocá-la no pós-checkout? 

Obrigado.

**Comment by gusfune** [comment]
Ta no beta, verifica e me confirma se ta 100%?

**Comment by eduardoamuri** [comment]
Faltou só o link para a prática de bem-vindo: https://beta.olugar.org/pratica/bem-vindo/

Sei que posso colocar direto na page do wordpress, mas preciso que fique dinâmico, certo? No beta, o link para o BETA, em PRD o link para PRD. Pode ajeitar isso? Acho que com um %alias resolve, né?

No mais, tudo certo, podemos subir para PRD. 

@gustavogitti , revisa o texto?

**Comment by gusfune** [comment]
Corrigido.
Essa página ta dentro do Wordpress, editável. Pode alterar direto ela em prod.

**Comment by eduardoamuri** [comment]
@gustavogitti vai ajeitá-la hoje, subimos em seguida.

**Comment by gusfune** [comment]
Subi a tela pois envolvia outra correção junto.
