### ISSUE TITLE
Liberar acesso ao app no Facebook

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#65]
Existe um app na área de developer do Facebook, preciso do acesso pra poder corrigir um problema ligado ao FB.

**Comment by eduardoamuri** [comment]
@gustavogitti vai dar uma olhada! :)

**Comment by gusfune** [comment]
Conseguiram localizar o app? Ta com algum de vocês ou ficou perdido?

**Comment by gustavogitti** [comment]
Não está com o Fabio, Gus. Como fazemos? Você não quer vincular a um novo que você gerencia?

**Comment by gusfune** [comment]
Farei isso.

**Comment by gusfune** [comment]
Fechando e recriando.
