### ISSUE TITLE
Avaliar e otimizar SSL do Lugar

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#69]
Relizar teste SSL Labs

**Comment by eduardoamuri** [comment]
Precisa de alguma intervenção minha aqui?

**Comment by gusfune** [comment]
Nope, isso é comigo só.

**Comment by gusfune** [comment]
Nota A+! Perfeito.
<img width="1073" alt="screenshot 2017-04-11 22 34 18" src="https://cloud.githubusercontent.com/assets/1147240/24937427/0603d8fa-1f07-11e7-9316-4a724d8589d0.png">
