### ISSUE TITLE
Ajuste de CSS nas práticas com Percurso

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#7]
Nas práticas que mostram o percurso ao lado, tem de acertar o espaçamento do menu lateral pra ficar mais enxuto, de acordo com o screenshot. Subir também o corpo do texto (onde aparece o vídeo) pra ele ficar mais próximo da faixa cinza, também como está no screenshot "thumb-emocao...". 

![thumb-emocao-pra-boost-sem-play](https://cloud.githubusercontent.com/assets/1147240/17953740/52131668-6a4c-11e6-92f9-b97ef015c7d6.png)

**Comment by gusfune** [comment]
Vê se ta melhor agora, mas provavelmente seja coisa de micro-ajuste dos pixels agora.

**Comment by gustavogitti** [comment]
Tá quase. Pra alinhar melhor a palavra "PERCURSO", coloca 10px em vez de 16px no class ".praticas"

E coloca 40px em vez de 50px antes de começar o corpo do post (em .main).

Daí fica perfeito!

**Comment by gusfune** [comment]
Feito, já vou subir direto em Produção.
