### ISSUE TITLE
URGENTE - O lugar acessível para usuários não logados

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#70]
Vídeo explicativo: 

[t_video5100727496014299139.mp4.zip](https://github.com/olugar/olugar/files/873733/t_video5100727496014299139.mp4.zip)

Além disso, precisamos atualizar o robots.txt, para evitar que o site seja indexado pelo Google.

**Comment by gusfune** [comment]
Bloqueei no robots.txt, mas ainda procurando uma solução definitiva, fiz na issue #71.
