### ISSUE TITLE
Melhorar redirect de não membros

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#72]
Alterar o redirect para verificar assinantes ao invés de não logados.

**Comment by gustavogitti** [comment]
Isso vai corrigir olugar.org que tá abrindo a home aberta (quando tô logado e assinante) em vez de abrir a home fechada? Eu não consigo mais acessar a home fechada!

**Comment by eduardoamuri** [comment]
@gusfune @gustavogitti eu acho que esse problema acontece porque os usuários estão sem membership ativo no wp (membership do woo).

Fui ajeitar agora, mas o admin tá me dando tela branca, talvez seja minha conexão.

Checam aí?

**Comment by gusfune** [comment]
Ele redireciona pra home aberta se o usuário não tiver assinatura ativa, mesmo logado.
Já fiz o fix pra melhorar isso, mas funciona dessa forma.
