### ISSUE TITLE
Remover "o lugar" do Google Maps

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#76]
Gus, eu inseri e agora não consigo mais mudar. Sugeri edições já duas vezes, falando que é PapodeHomem lá, mas ele segue vinculando esse endereço ao lugar.org e aparece na busca... Isso fode com a gente pois passa a mensagem de que o lugar é uma sala em São Paulo...

Sabe como remover de vez isso?

![screen shot 2017-03-30 at 11 09 49](https://cloud.githubusercontent.com/assets/21227612/24508375/98968762-1539-11e7-962c-184eff36323c.png)

**Comment by eduardoamuri** [comment]
Resolvemos. :)
