### ISSUE TITLE
Problema no botão de voltar no browser

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#78]
Gus, tô no Firefox do Mac, mas isso só acontece no site do lugar, não em outros. É recente.

Quando vou para uma página (tipo uma prática)
![screen shot 2017-03-30 at 11 30 22](https://cloud.githubusercontent.com/assets/21227612/24509318/6e75460a-153c-11e7-95c3-8c94d34b87a0.png)
 e volto, ele não volta, fica na mesma página. E some o vídeo! Segue screenshot. Tenta replicar aí.

Abraço.

**Comment by eduardoamuri** [comment]
Não está mais acontecendo.
