### ISSUE TITLE
Erros nas telas do wp-admin (especialmente na tela de usuários)

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#79]
https://olugar.org/wp-admin/profile.php

o que será, gus? não carrega nada.

**Comment by eduardoamuri** [comment]
Esse bug está acontecendo para as buscas no WP-ADMIN também, de usuário. 

É só digitar o nome de usuário e dar um "Pesquisar" que dá tela branca.

**Comment by eduardoamuri** [comment]
O mesmo erro acontece quando tentamos customizar algo na página, ou quando clicamos nos números da paginação.

**Comment by eduardoamuri** [comment]
Issue resolvida.
