### ISSUE TITLE
Problema de embed nas práticas

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#8]
Também nas práticas algo fez com que o embed do Vimeo ficasse com duas faixas pretas, em cima e embaixo. O embed está certo:

`<iframe src="https://player.vimeo.com/video/158036949?color=1abc9c&amp;title=0&amp;byline=0&amp;portrait=0" width="640" height="360" frameborder="0" allowfullscreen="allowfullscreen"></iframe>`

**Comment by gustavogitti** [comment]
Todos, Gus, todos. Exemplo:

https://olugar.org/pratica/sem-continuidade-sem-chance/

**Comment by gusfune** [comment]
Acho que agora fui, subi no beta correção.

**Comment by eduardoamuri** [comment]
Perfeito, pode subir em PRD.

**Comment by gustavogitti** [comment]
Pode subir, tá certo!
