### ISSUE TITLE
Colocar marca do lugar em vez da do WP na tela wp-login.php

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#80]
gus, pode trocar? segue a marca.
![olugar_azul_web](https://cloud.githubusercontent.com/assets/21227612/24516296/7fab437a-1550-11e7-8f71-66f5a9016847.png)

**Comment by gusfune** [comment]
Feito, ta no Beta pra validar.

**Comment by eduardoamuri** [comment]
Validado.
