### ISSUE TITLE
Gerar sitemap para o Google Webmaster (ou outra solução para limpar a indexação do Google)

### ISSUE THREAD

**Issue by gustavogitti** [olugar/olugar#82]
@gusfune, as páginas estão fechadas, mas ainda seguem sendo listadas pelo Google e também visíveis pra quem clica em "ver cache" (https://www.google.com.br/?gws_rd=cr&ei=ecjeWMWTHMmXwQT487HYDg#q=site:olugar.org&*).

Tentei remover individualmente pelo Google URL Remover, mas temos mais de 1000 membros com várias URLs por pessoa (/activity /replies etc).

Você sabe como atualizar a indexação do Google? Pensei em gerar um sitemap e subir no Google Webmaster (não tem nenhum sitemap lá atualmente). Eu costumo usar esse: https://br.wordpress.org/plugins/google-sitemap-generator/

O que acha? Tem solução melhor? @eduardoamuri 

Abraço!

**Comment by gusfune** [comment]
Eu já fiz isso @gustavogitti, fiz o sitemap na mão apenas das páginas públicas. Vide: https://olugar.org/sitemap.xml
Fiz uma correção pra enviar pro Google WebMaster Console, agora esperar.
A priori ta mapeado apenas o que é público, resto nem aparece no sitemap.
