### ISSUE TITLE
Testar upgrade do WooCommerce 3.0

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#83]
Saiu nova versão do WooCommerce, precisamos subir no Beta e testar pra ver se vai tudo funcionar de acordo, pois a gente fica travado agora sem update com esse major release.

**Comment by gusfune** [comment]
Vou deixar esse item na fila @eduardoamuri e @gustavogitti até fechar os itens pra validação, pois esse se der erro vai quebrar a validação de tudo em aberto. Aviso assim que for pra retomarmos.

**Comment by gusfune** [comment]
@eduardoamuri e @gustavogitti, ta feito já no BETA. Podem conferir e ver se ta tudo 100%?
Estando ok, eu dou prosseguimento a issue de #86 refatorar o processo de renovação.

**Comment by eduardoamuri** [comment]
Tudo ok. :)

**Comment by gusfune** [comment]
Feito em prod, pode testar e fechar se estiver 100%?
