### ISSUE TITLE
Alterar design da página de perfil

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#84]
Gostaríamos de tirar a header image (o banner). Ninguém o utiliza hoje. 

Com isso, o bloco de texto sobe. Mudar a cor do @ de perfil para preto.

**Comment by gusfune** [comment]
![exemplo](https://cloud.githubusercontent.com/assets/1147240/24931184/bd1318be-1ee2-11e7-8ece-3e2f1265af49.png)

**Comment by gusfune** [comment]
Ajustes feitos, validar no Beta pra gente subir.
https://beta.olugar.org/pessoas/eduardoamuri/

**Comment by eduardoamuri** [comment]
Gus, não mudou nada por aqui. 

![screen shot 2017-04-13 at 8 12 46 am](https://cloud.githubusercontent.com/assets/247457/25002476/0771605c-2021-11e7-9005-87301f9a835f.png)

Já limpei cache.

**Comment by gusfune** [comment]
Resolvido, tenta de novo?

**Comment by eduardoamuri** [comment]
Gus, não validei no desk ainda, mas ficou estranho no mobile, metade do nome do usuário ficou para fora, meio desalinhado, rola dar um tapa?

**Comment by gusfune** [comment]
Subi um fix, da uma conferida?
