### ISSUE TITLE
Refatorar fluxo de renovação

### ISSUE THREAD

**Issue by eduardoamuri** [olugar/olugar#86]
Explicaremos em reunião, 11/04/17.

**Comment by gusfune** [comment]
To vendo aqui e a forma "correta" pro usuário renovar seria através da página "minha conta" e ir em assinaturas: https://olugar.org/minha-conta/subscriptions/

Porém, os adicionados manualmente não tem acesso a isso.

A melhor solução possível seria alterarmos a tela de "voltar" de forma que o usuário faça login direto nela, e feito o login, redireciona direto pra tela de check-out.

Também podemos editar a tela de conteúdo restrito pra verificar se o usuário está logado, e caso ele tenha uma assinatura vencida, alterar o conteúdo da página para explicar o processo de renovação.

Essa seria a solução mais simples e que "resolveria" de forma eficiente até o dia que conseguirem todos os membros integrados no sistema automático como Stripe.

Tendo ok de vocês, seguimos dessa forma.

### Recapitulando
1. Alteramos a tela de conteúdo restrito para exibir o conteúdo de acordo com o status de assinatura do usuário.
2. Ele loga nessa tela e vai direto pro checkout pra renovação.
3. Mantemos uma tela de renovação pra usuários deslogados, em que ele pode logar e ir direto pro check-out.

O que acham?
Só também precisamos definir se a URL vai ser `/voltar` ou `/renovacao`. Como prefere?

**Comment by eduardoamuri** [comment]
@gustavogitti

**Comment by gusfune** [comment]
Para controle próprio, o que será feito:
- [ ] Refatorar a tela de "conteúdo restrito" para que ela funcione de forma dinâmica (dentre não logado, logado ex-membro)
- [ ] Customizar a exibição de mensagem de acordo com o status do usuário logado
- [ ] Exibir *call-to-action* de renovação caso o usuário esteja logado e com assinatura expirada
- [ ] Criar uma página separada de renovação para não-logados

**Comment by gusfune** [comment]
Consegui montar isso de uma forma BEM simplificado que acho que vai resolver o problema.
- Basicamente eu "reajustei" a página de voltar: https://beta.olugar.org/voltar/
- O usuário quando cai nessa tela se depara com dois cenários:
  - Caso deslogado, é exibido o formulário de login que redireciona direto pro finalizar compra com a assinatura no carrinho.
  - Caso logado, aparece um link pra ele clicar e redireciona pro finalizar compra.

Essa tela não ta bloqueada no membership, e tem um link pra ela no primeiro parágrafo de https://beta.olugar.org/restrito/ - outra vantagem é que mandando esse link direto pra qualquer ex-membro, o processo de renovar fica extremamente simples.

O que acham? Fiz da forma mais simples possível pra facilitar.
Estando ok, eu vou precisar que me passem os textos de usuário logado e deslogado, pra configurar na página e na sequência subo no admin.

**Comment by eduardoamuri** [comment]
@gustavogitti que achou?

**Comment by gustavogitti** [comment]
Ficou ótimo!

O texto de não logado tá quase 100%, só mudar o corpo pra isso (a linha fina abaixo do título e o título da página estão perfeitos):

Entre abaixo com os dados de acesso que você usava. Você será redirecionado para finalizar o pagamento e pronto, bem-vindo de volta ao lugar!

Seu nome de usuário ou email:

Sua senha:

...

Gus, rola de entrar com email em vez de nome de usuário, então? Isso tá testado?

**Comment by gustavogitti** [comment]
Texto para logado (o resto está OK, mas remova a imagem "Quero entrar também):

Para voltar, clique aqui, preencha os dados para renovar a assinatura e pronto, seu acesso será liberado.

**Comment by gusfune** [comment]
@gustavogitti, o login por email não rola, tem que ser por username mesmo.
Fiz os ajustes de texto, pode validar uma última vez antes de subir em produção?

**Comment by gustavogitti** [comment]
Gus,

Na página NÃO LOGADO, o texto não está como coloquei. 

TROQUE: Quer voltar para o lugar? Entre abaixo com seu login/senha antigo, você será redirecionado para a página de finalizar compra. Após a conclusão do pagamento você estará de volta no lugar.

POR: Entre abaixo com os dados de acesso que você usava. Você será redirecionado para finalizar o pagamento e pronto, bem-vindo de volta ao lugar!

E troque o "Fazer login" por "Entrar" no botão.

...

Na página LOGADO, está um texto sem sentido:

"Entre abaixo com os dados de acesso que você usava. Você será redirecionado para finalizar o pagamento e pronto, bem-vindo de volta ao lugar!

Para voltar, clique aqui, preencha os dados para renovar a assinatura e pronto, seu acesso será liberado."

Deixe apenas (o link fica apenas no "Clique aqui"): 

Para voltar, **clique aqui**, preencha os dados para renovar a assinatura e pronto, seu acesso será liberado.

**Comment by gusfune** [comment]
@gustavogitti fiz os ajustes. Valida, estando ok subimos em produção!

**Comment by gusfune** [comment]
No ar!

**Comment by eduardoamuri** [comment]
Gus

**Comment by gusfune** [comment]
Subi o bigode, mas não entendi como quer que ajuste a coluna, me explica melhor como quer?

**Comment by eduardoamuri** [comment]
É só tirar o max-width do bigode, Gus, pro texto pegar a coluna toda. :)

**Comment by gusfune** [comment]
Se alterar isso nessa página, afeta em outras com bigode, ajustamos isso? Ou só nessa página?

**Comment by eduardoamuri** [comment]
@gustavogitti ajuda?

**Comment by gustavogitti** [comment]
Pode ser só nessa página. Cria uma nova class. Depois a gente pensa nas outras com calma.

**Comment by gusfune** [comment]
Subo no Beta, validando subimos!
