### ISSUE TITLE
Ajustes de CSS em post do blog

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#9]
No post do blog aberto, o título e o subtítulo estão com largura maior do que o corpo do texto. E eu montei as chamadas sempre pra alinhar, então agora está tudo com espaço muito grande. Você consegue deixar como era, com o título e o subtítulo tendo a mesma largura que o corpo do texto abaixo?

**Comment by gusfune** [comment]
Pode me explicar melhor esse item @gustavogitti? Fiquei confuso aqui pq pelo grid estão alinhados, mas talvez eu não esteja conseguindo visualizar.

**Comment by gustavogitti** [comment]
Olha como está feio:

![screen shot 2016-08-31 at 10 19 22 am](https://cloud.githubusercontent.com/assets/21227612/18130195/70e88524-6f64-11e6-9a76-90167cc2d059.png)

Antes o título e o subtítulo ficavam com a largura menor, igual à do corpo do post (acho que passando pouco, tipo uns 640px total). Entendeu?

**Comment by gusfune** [comment]
Entendido, vê se agora ta melhor? Ta só no beta.
https://beta.olugar.org/como-nao-ter-mais-problemas/

**Comment by eduardoamuri** [comment]
Perfeito, Gus.

**Comment by gusfune** [comment]
Ta no ar então!
