### ISSUE TITLE
Configuração do Medium do Lugar

### ISSUE THREAD

**Issue by gusfune** [olugar/olugar#98]
Configurar de acordo com o email enviado hoje cedo.

**Comment by gusfune** [comment]
Ta feito já @gustavogitti e @eduardoamuri, falta só responder o email do Medium dizendo que os DNS foram configurados. Feito isso em até 24h respondem confirmando a configuração e ta tudo certo pra rodar em blog.olugar.org.

**Comment by eduardoamuri** [comment]
@gustavogitti chegou?

**Comment by eduardoamuri** [comment]
Tudo certo aqui, Gus. 

Obrigado.
